kubeless/kubeless

cmd/root.go
pkg/controller/controller.go

`kubeless install` command can panic when no kubernetes cluster is available, like the following:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45eb0d]
goroutine 1 [running]:
panic(0x1adc6e0, 0xc420010250)
/usr/local/golang/src/runtime/panic.go:500 +0x1a1
github.com/skippbox/kubeless/cmd.newControllerConfig(0x0, 0x0, 0x1cce16e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/skippbox/kubeless/cmd/root.go:75 +0x1bd
github.com/skippbox/kubeless/cmd.glob..func5(0x2b87a00, 0x2bfa458, 0x0, 0x0)
/go/src/github.com/skippbox/kubeless/cmd/install.go:41 +0x207
github.com/skippbox/kubeless/vendor/github.com/spf13/cobra.(*Command).execute(0x2b87a00, 0x2bfa458, 0x0, 0x0, 0x2b87a00, 0x2bfa458) …
```

cmd,pkg: fix nil dereference when running kubeless install

---

glide.lock
glide.yaml

Add the following packages to `glide.*`, to make `"glide list"` work without any dependency error.
* github.com/docker/spdystream
* github.com/renstrom/dedent
* k8s.io/heapster/metrics/apis/metrics/v1alpha1

glide: add more packages to resolve dependency errors

---

examples/minio/README.md
examples/minio/minio-test.py
examples/minio/minio/.helmignore
examples/minio/minio/Chart.yaml
examples/minio/minio/README.md
examples/minio/minio/templates/NOTES.txt
examples/minio/minio/templates/_helpers.tpl
examples/minio/minio/templates/minio_deployment.yaml
examples/minio/minio/templates/minio_distributed_configmap.yaml
examples/minio/minio/templates/minio_pvc.yaml
examples/minio/minio/templates/minio_secret.yaml
examples/minio/minio/templates/minio_statefulset.yaml
examples/minio/minio/templates/minio_svc.yaml
examples/minio/minio/templates/minioconfig_configmap.yaml
examples/minio/minio/values.yaml
examples/minio/requirements.txt

This also contains a minio chart, which we can remove later once it is in the charts stable repo.
we will just be able to install it with:
```
helm install stable/minio
```

add minio example

---

cmd/kubeless/install.go

Since "kubeless install" is a non-destructive operation, I propose we default to "yes" if you just hit enter.

Default to YES when installing Kubeless

---

cmd/kubeless/install.go
cmd/kubeless/topicCreate.go
cmd/kubeless/topicDelete.go
cmd/kubeless/topicList.go
cmd/kubeless/topicPublish.go
pkg/controller/controller.go
pkg/utils/k8sutil.go

I have made the K8s namespace that Kubeless installs on configurable for multi-user clusters.
There's some clear refactorings in the future:
- The namespace switch needs to be passed to each command, which isn't ideal
- There's a lot of passing around of ctlNamespace which could probably be obtained from somewhere central (maybe by setting DefaultNamespace in pkg/utils/k8sutil.go?
- pkg/utils/k8sutil.go hardcodes the internal hosts and ports, they might also ideally be pulled from context and configurable as well

Allow using a custom namespace for the kubeless controller

---

cmd/kubeless/topic.go
cmd/kubeless/topicCreate.go
cmd/kubeless/topicDelete.go
cmd/kubeless/topicList.go
cmd/kubeless/topicPublish.go

The `topic` command was broken (only the `publish` verb was working).
This fixes that.
Also, I've renamed the flag so it clearer now (it would be possible to have kafka running in a different k8s namespace than the kubeless controller).

fix for kafka namespace flag

---

docker/events/kubernetes/Dockerfile
docker/events/kubernetes/README.md
docker/events/kubernetes/events.py
docker/events/kubernetes/local-events.py
examples/minio/slack/Makefile
examples/slack/Makefile
examples/slack/README.md
examples/slack/botevents.py

This is an example of writing a kubernetes events "bridge" to the kubeless kafka.
The container `skippbox/k8s-events:0.10.12` will listen to events using the python client and produce messages onto a `k8s` kafka topic.
Then there is a SLACK function example, which gets triggered on the `k8s` topic and published the events to SLACK.

A container to sync k8s events and examples

---

pkg/utils/k8sutil.go

using `jbianquettibitnami/kubeless-ruby:0.0.0` runtime image from PR https://github.com/bitnami/kubeless/pull/92.

adding ruby support

---

cmd/kubeless/call.go

For:
```
kubeless function call unknownfunc
```
There is a panic.

Report error for calling unknown function name.

---

pkg/controller/controller.go

The root problem of #117 is kubeless controller makes return for whatever unexpected errors the monitor function might have. It leads to the stop watching of the controller immediately.
This PR aims to keep the controller keep running all the time.

keep controller running all the time

---

docker/runtime/python-2.7/Dockerfile
docker/runtime/python-2.7/kubeless.py

Are you sitting down?  This change allows the python runtime to
handle *more than one request at a time* - I love living in the
future!
In particular: this allows the python runtime to continue responding
to livenessProbes even when the function is doing something time
consuming (like making a request to another remote service).
This change rewrites the python runtime to use a multithreaded
server (uwsgi), while keeping the same bottle-based python API.
Parallelism can be tweaked by using the UWSGI_PROCESSES/UWSGI_THREADS
container environment variables (default is a fairly modest 4/2).
Fixes #142

Rewrite python2.7 runtime to use bottle/uwsgi

---

docker/events/event-consumer/Dockerfile
docker/events/event-consumer/kubeless.py
docker/runtime/python-2.7/Dockerfile
docker/runtime/python-2.7/kubeless.py
examples/python/function1.yaml
manifests/monitoring/prometheus.yaml
pkg/utils/k8sutil.go

Exports basic function_duration_seconds histogram, and
function_{calls,failures}_total counters, all labelled with HTTP
method.
Also adds prometheus annotations to function Deployment.

Add prometheus /metrics endpoint to python runtime

---

manifests/README.md
manifests/controller/controller-deployment.yaml
manifests/controller/controller-svc.yaml
manifests/tpr/function.yaml
manifests/ui/ui-deployment.yaml
manifests/ui/ui-svc.yaml

This finishes the basic manifests to start kubeless with `kubectl create` instead of `kubeless install`.
There is definitely some polishing to do: Check that we can scale zk , add probes with good timeouts etc...
But this can be the basis for a complete chart and a ksonnet example.
cc/ @ngtuna @anguslees

finish manifests to start everything

---

cmd/kubeless-controller/kubeless-controller.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/utils/k8sutil.go

This PR appends `ownerReferences` field to each deployed svc/cm/deployment which points to their belonged function tpr object. So if the function is deleted, they will become orphaned objects. A garbage collector is added to scan every minutes orphaned deploy/cm/svc then clean them.
cc/ @anguslees

Add garbage collector to kubeless controller

---

.travis.yml

`cd bundles` in before_deploy section makes the current directory changes to bundles that causes `No such file or directory` error in later commands

correct pwd in before_deploy section

---

kubeless.jsonnet
manifests/kafka/kafka-stateful.yaml
manifests/zookeeper/zk-headless-svc.yaml
manifests/zookeeper/zk-stateful.yaml
manifests/zookeeper/zk-svc.yaml

I was getting started checking on out kubeless on my minikube install and noticed that none of the `kubeless topic` commands were working for me. I was able to determine that this is because the topic commands search for a label of `kubeless=kafka` to get the pods it issues commands against. That was [introduced here](https://github.com/kubeless/kubeless/commit/7f74dba0680a9a2698b8a71860ab7d322d104dd5).  
The current manifest for kafka, however, still uses the `app=kafka` label. This PR updates the labels for the kafka stateful set to match the expected `kubeless=kafka`.

Update labels to use kubeless key instead of app

---

docker/controller/Dockerfile
docker/runtime/python-2.7/event-trigger/Dockerfile
docker/runtime/python-2.7/http-trigger/Dockerfile
docker/runtime/python-3.4/event-trigger/Dockerfile
docker/runtime/python-3.4/event-trigger/kubeless.py
docker/runtime/python-3.4/http-trigger/Dockerfile
docker/runtime/python-3.4/http-trigger/kubeless.py

this removes alpine base image, adds 3.4 runtimes (without actually adding them in the go code).
minor detail in controller image.
Plus check of env variable to remove the hard-coded kafka endpoint (to be able to support existing kafka clusters).
@ngtuna I think you should merge this before adding the modifications for non-root

Improve Dockerfiles and add 3.4 runtime

---

docker/runtime/nodejs-6.10/http-trigger/.eslintrc.js
docker/runtime/nodejs-6.10/http-trigger/.gitignore
docker/runtime/nodejs-6.10/http-trigger/Dockerfile
docker/runtime/nodejs-6.10/http-trigger/kubeless.js
docker/runtime/nodejs-6.10/http-trigger/package.json
examples/nodejs/hellowithdata.js
pkg/utils/k8sutil.go

This PR rewrites the NodeJS support for Kubeless. These are the major changes: 
- Now the functions are served using [Express](https://expressjs.com/)
- Support for liveness probe in the URL `/healthz`
- Support for prometheus metrics in the URL `/metrics`. The exposed metrics are:
- Access counter per method (GET/POST)
- Error counter per method
- Histogram about function duration.
It also adapt the existing Dockerfile and the NodeJS example.
Note that for retrieving metrics, if the user function is asynchronous, it should return a `Promise`.

Improve NodeJS runtime support

---

Makefile
script/minikube-rbac-test

Add basic smoke testing for success/failure with/out RBAC role,
example run:
```
$ make minikube-rbac-test 
./script/minikube-rbac-test
INFO: VERIFY: k8s tools installed: minikube kubectl kubecfg kubeless
INFO: VERIFY: minikube running ...
INFO: VERIFY: minikube running with RBAC ... 
INFO: RBAC TEST: function deploy/call must fail without RBAC roles
INFO: Deleting function in case still present ... 
INFO: Delete kubeless namespace, wait to be gone ... 
namespace "kubeless" created
INFO: Waiting for kubeless controller to be ready ... 
INFO: Deploying function ...
INFO: Waiting for controller to show logline 'User.*cannot' ...
PASS: Found logline: 'User.*cannot'
INFO: Calling function, expecting rc=1 
PASS: called function, got rc=1
INFO: RBAC TEST: function deploy/call must succeed with …
```

[jjo] add minikube-rbac-test

---

kubeless-rbac.jsonnet

#OCD~ish: get kubecfg diff --diff-strategy subset to be zero:
* before: https://gist.github.com/jjo/e95c105b1039456735ecf9b6c3eb6b3a
* after: https://gist.github.com/jjo/a8c68931fdfc6fb7346d25d3f61ba0fc

[jjo] narrow clusterRoleBinding fields,

---

helm/kubeless/Chart.yaml
helm/kubeless/templates/_helpers.tpl
helm/kubeless/templates/ui-deployment.yaml

The chart was referencing a `chartref` template that didn't exist,
this PR removes the template.
cc @sameersbn @rimusz

chart: fix missing label template

---

pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

Show the available runtimes in the error message when the given one is not valid:
Ex:
```
The given runtime and version 'nodejs3' does not have a valid image for HTTP based functions. Available runtimes are: python2.7, node6, node8, ruby2.4
```

Improve error message for available runtimes

---

docker/runtime/nodejs/http-trigger/kubeless.js
docker/runtime/nodejs/http-trigger/package.json
pkg/utils/k8sutil.go

This PR adds support for:
- JSON encoded requests
- CORS requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
- Accept any request path. Previously if the server received a request in any path different than `/` the server returned a 404.

Add CORS and subpaths support  for NodeJS functions

---

chart/kubeless/templates/kafka-headless-svc.yaml

A bug in helm causes "object not found" error to be thrown while
deleting a release if any template contains a leading YAML seperator.
Fixes #239

leading YAML seperator in templates cause "object not found" error

---

.travis.yml
examples/Makefile
script/cluster-up-dind.sh
script/cluster-up-minikube.sh
script/integration-tests
script/libtest.bash
tests/integration-tests.bats

* update kubecfg to v0.4.0 release
* add @ngtuna's pubsub, func-metadata tests
* add minikube support, requires building
`nsenter` as travis/trusty doesn't have it
while `minikube --vm-driver=none` requires
it
* add ./script/cluster-up-{dind,minikube}.sh
to potentially use any of them, selectable
via TRAVIS_K8S_CONTEXT envvar
* default to minikube
* dump logs on errored builds
* use added _wait_for_kubeless_controller_ready when testing
pubsub-* function(s)
* cleanup: remove unused kubeless_function_exp_regex_call

switch to minikube, add @ngtuna's pubsub

---

manifests/README.md
manifests/ingress/ingress-controller-http-only.yaml

Minor change to the ingress-controller manifest to support http only. For https setup, Adnan and I are going to submit documentation.

ingress controller http only

---

examples/Makefile
kubeless.jsonnet
script/integration-tests
script/libtest.bash
tests/integration-tests.bats

* integration-tests.bats: enable `pubsub`
* harden `kafka-0` readiness checks to (more) deterministically run
`make -C examples pubsub pubsub-verify`
- add livenessProbe to kafka-0:
added tcp port 9092 probing, specially needed when testing (i.e. full
minikube/dind cluster being brought up), kafka startup have been
observed to fail from e.g. `zookeeper.kubeless` failed resolution
(kube-dns may have not completely settled), and its containers'
`/run.sh` does a single shot run w/o retry
- enhance related functions:
` _wait_for_kubeless_kafka_{server,topic}_ready`
- tail the whole log, to avoid races
* misc:
- add TRAVIS_DUMP_LOGS for force log dumping even if successful
- only delete func if not present

[jjo] enable pubsub integration tests

---

pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

The nodejs runtimes are called nodejs6 and nodejs8, but the error messages if you used a wrong runtime name were wrong, specifying "node6" and "node8" instead. 
This pull request fixes that error message to the correct runtime name.

Fix error message about the list of available runtimes.

---

kubeless-rbac.jsonnet

kubectl validates the rbac yaml file and throws this below error due to the `ClusterRoleBinding.roleRef` doesn't have `apiGroup`. This PR fixes that.
```
error validating data: field roleRef.apiGroup for v1beta1.RoleRef is required; if you choose to ignore these errors, turn validation off with --validate=false
```

hotfix validating kubeless-rbac yaml

---

pkg/utils/k8sutil.go

If func is deployed via REST request with the func spec contains custom runtime image, then we shall accept it.

Allow custom runtime declared via func spec

---

cmd/kubeless/ingressCreate.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

Hi,
I'm playing around with `kubeless` on Google Container Engine. I came across the `kubeless ingress` subcommands, but the created Ingress misses configuration for `kube-lego`, which uses LetsEncrypt for adding certificates to Ingresses automatically. With this PR I'm adding a flag which triggers the needed configuration of the Ingress: `kubeless ingress create ... --enableTLSAcme`
Greetings,
Marc

Added kube-lego support for ingress creation

---

docker/runtime/ruby-2.4/http-trigger/Dockerfile
docker/runtime/ruby-2.4/http-trigger/kubeless.rb
examples/Makefile
examples/ruby/function.yaml
examples/ruby/helloget.rb
examples/ruby/hellowithdata.rb
examples/ruby/latest.rb
pkg/utils/k8sutil.go
tests/integration-tests.bats

- made functions easier to define - now you just need to define the
function like with Python and don't need to wrap it in a class
- handler function name is respected and the runtime will now run your
function with that name instead of relying on the harcoded
Kubelessfunction.run to exist
- $stdout.sync is set to true so that stdout output is not buffered and
printed straight away
- idiomatic improves to the Ruby runtime
- add tests for Ruby runtime
**NOTE**: This is a **breaking** change to the Ruby runtime, functions will need to be updated. e.g.
```
class Kubelessruntime
def self.run(request)
...
end   
end
```
would need to be updated to:
```
def run(request)
...
end
```

ruby runtime improvements

---

pkg/utils/k8sutil.go

I got the following error when running `kubeless update ...`:
```
FATA[0000] open .func.json: permission denied
```
because I was in a folder without write permissions. This PR uses `os.TempDir()` to retrieve a folder in which the user will have write access.

Use a temporary dir when writting .func.json

---

cmd/kubeless/deploy.go
cmd/kubeless/describe.go
cmd/kubeless/ingressList.go
cmd/kubeless/list.go
pkg/controller/controller.go
pkg/spec/spec.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

$ kubeless function deploy --schedule "*/1 * * * *" --runtime python2.7 --handler helloget.foo --from-file python/helloget.py
- create cronjob object instead of deploy and svc
- inject configmap to cronjob
- keep initContiner for cronjob to support loading function dependency (I am not really sure about this case)
- keep livenessProbe, prometheus annotations
- refactor EnsureK8sResources()

support scheduled function

---

docker/runtime/ruby-2.4/event-trigger/Dockerfile
docker/runtime/ruby-2.4/event-trigger/kubeless.rb
examples/Makefile
examples/ruby/helloevent.rb
pkg/utils/k8sutil.go
script/libtest.bash
tests/integration-tests.bats

Adds the event-trigger implementation for the ruby 2.4 runtime. I've
modified the way the function is called, it now gets the Ruby class
name from the FUNC_NAME and loads that as a constant. If we want to
keep this as-is, I can undo that change.
I've also intentionally left out prometheus metrics, I think that can
be added from someone with more prometheus knowledge in a later PR.

ruby: adds event trigger support

---

manifests/autoscaling/README.md
manifests/autoscaling/custom-metrics.yaml
manifests/autoscaling/prometheus-operator.yaml
manifests/autoscaling/sample-metrics-app.yaml
manifests/autoscaling/sample-prometheus-instance.yaml

These manifests worked in kubeadm-dind-cluster. They are also work in other k8s environments if the cluster configuration is set properly (kube-controller-manager and kube-apiserver)
cc/ @arapulido @sebgoa

add autoscaling manifests

---

README.md

When publishing a message under a topic the function should read it as `context` not `context.json` since it is a string

Fix PubSub example

---

cmd/kubeless/list.go
cmd/kubeless/list_test.go

Parse Node.js dependencies when executing `kubeless function ls`:
```
NAME 	NAMESPACE	HANDLER           	RUNTIME	TYPE  	TOPIC	DEPENDENCIES
test	default  	hello.handler     	nodejs6	HTTP  	     	lodash: ^1.0.0
strftime: ^0.9.2
```
Fixes #213

Print parsed dependencies

---

README.md
cmd/kubeless/deploy.go
cmd/kubeless/update.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

This PR elaborates the explanation of the command `function deploy` in the main README. Apart from that it shows the available runtimes when executing `function deploy|update --help`.
Fixes #281

Improve explanation of deploy command

---

docs/runtimes.md
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

This PR allows users to specify `--env NPM_SCOPE=@myorg` and `--env NPM_REGISTRY=http://myregistry.com` to specify custom scopes and registries when installing NPM modules.
Fixes #306

Allow to use a custom npm scope and registry

---

cmd/kubeless/topicPublish.go
examples/Makefile

It also simplifies the way messages are published. Fixes #333
Ensured with an integration test.

Avoid the need to scape characters when publishing messages

---

pkg/utils/k8sutil.go
script/libtest.bash

Use `DeletePropagationBackground` instead of `DeletePropagationForeground`.
This fixes #324 since the `Foreground` policy causes that after trying to recreate (delete + deploy), the controller tries to patch the deployment that is being terminated instead of creating a new one.
I checked that after deleting the function everything is cleaned up with the `Background` policy so this PR should not cause a regression regarding https://github.com/kubeless/kubeless/pull/279

Fix deployment recreation

---

cmd/kubeless/deploy.go
cmd/kubeless/function.go
cmd/kubeless/function_test.go
cmd/kubeless/update.go
examples/Makefile
pkg/utils/k8sutil.go
script/libtest.bash
tests/integration-tests.bats

Right now the `update` commands builds a new `Function` object from zero and sends it to the backend to deploy it. Basically it is like the `deploy` command but with less options.
With this PR we retrieve the existing function (and returns an error if the function doesn't exist yet) and we only update the fields that the user introduces ensuring that we are not overwriting previous values.
Fixes #337

Update command refactor

---

.travis.yml
script/binary-cli
script/binary-controller

Remove the builds for OS X, Go 1.7 and 386 binaries since they are not being used.
Fixes #343

Remove unused platforms

---

.travis.yml
script/release_notes.sh

This PR changes the release process to:
- Create a draft instead of directly releasing a new version
- Auto generate the release notes with the commits/PR included in the release
Eg. For the version 0.2.2 it will generate the message (note that the commit list should be purged to avoid useless info):
---------
This release include the following commits and features:
- ae5437d0 Update command refactor (#340)
- d922f447 Adding contributing documentation (#346)
- abb6223d Add support for custom runtime images in CLI (#323)
- ec6e5385 Merge pull request #332 from andresmgot/deploymentRemoval
- 6c26babf Merge pull request #316 from arjunrao87/pr/multi-env-vars
- 5e1736e0 Merge pull request #338 from andresmgot/quotes
- 8f6a84e0 Fix test
- db8391f9 Allow to use a custom npm scope and registry …

Auto generate release notes

---

README.md
docs/dev-guide.md

`kubeless install` no longer works and was removed in favor of a `kubectl create` of a manifest available in the release.
Also, bumps the version number to the latest release.

dev-guide: remove kubeless install

---

README.md
chart/kubeless/README.md
docs/architecture.md
script/kubeless_uninstall.sh

This is a follow up to https://github.com/kubeless/kubeless/pull/290
Since Kubeless migrated from Third Party Resource (TPR) to Custom
Resource Definition (CRD), the commands mentioned in the README were not
correct anymore. This patch updates the doc in a few places.
/cc @asymmetric

doc: replace tpr by crd

---

README.md

Hi, for new users it might not be obvious how to install kubeless with brew. Also the link within the current comment doesn't really clarify this. This PR extends the installation section slightly and improves the link along with it.
Cheers

Improve installation documentation

---

manifests/autoscaling/README.md

I found a parameter to adjust the HPA controller interval that would help to make it reacts quickly to the function's load. I tested it with 5s and the result was reasonable - The function was scaled up and down quickly. There might be harming the system by putting HPA under stress but that would just be a suggestion for optimization.

optimize HPA controller in autoscaling

---

pkg/utils/k8sutil.go

When no host name is specified we use the current config host name.
We are assuming that there will always have a port in the host name but it is not the case on a GKE cluster.
We might want to revisit what is used in the default host name on GKE. Maybe it would be better to use the cluster name or something else instead of the ip.
Fixes #379

ingress create command: fixed host parsing when no port is defined. 

---

kubeless-rbac.jsonnet

Avoid using `apiGroups: ["*"]`, explode rules to be narrower
per apiGroups×resources×verbs

[jjo] fix RBAC roles

---

pkg/utils/k8sutil.go

K8s already implements basic atomic logic like "create will fail if
already exists" and "delete will fail if already absent".  This change
removes unnecessary explicit checks that attempted to detect these
conditions.

Rely on k8s' atomic logic rather than our own check-before-do

---

examples/minio/slack/bot.py
examples/minio/slack/requirements.txt
examples/slack/botevents.py

The example fails silently when, for example, the Slack auth token is incorrect. Worse, it implies it succeeded by mentioning in the debug console that the message was sent

Add error reporting to Slack messages rather than fail silently

---

script/libtest.bash
tests/integration-tests.bats

* Add simple `kubeless ingress` and `autoscale` testing,
verify both expected `kubeless ... list` and k8s objects created
* Re-organize function update testing to have their own `bats` stanza,
eases isolating debugging
* make `k8s_wait_for_uniq_pod` general as `k8s_wait_for_pod_count`

[jjo] add simple ingress and autoscale testing

---

cmd/kubeless/call.go
pkg/utils/k8sutil.go

Minor refactor of the `call` code along with the `CRD|Rest|Client` generation of k8sutil

Refactor call method to avoid hardcoded URL

---

README.md
cmd/kubeless/deploy.go
cmd/kubeless/function.go
cmd/kubeless/list.go
cmd/kubeless/list_test.go
cmd/kubeless/update.go

Fixes #87 (Gives feedback to the users about the function deployment)
TODOs:
Output example:
```
▶ kubeless function deploy pubsub-python34 --trigger-topic s3-python34 --runtime python3.4 --handler pubsub.handler --from-file examples/python/pubsub.py
INFO[0000] Deploying function...
INFO[0000] Function post-nodejs submitted for deployment
INFO[0000] Check the deployment status executing 'kubeless function ls post-nodejs'
▶ kubeless function ls post-nodejs
NAME       	NAMESPACE	HANDLER              	RUNTIME	TYPE	TOPIC	DEPENDENCIES	STATUS
post-nodejs	default  	hellowithdata.handler	nodejs6	HTTP	     	            	0/1 NOT READY
▶ kubeless function ls post-nodejs
NAME       	NAMESPACE	HANDLER              	RUNTIME	TYPE	TOPIC	DEPENDENCIES	STATUS
post-nodejs	default  	hellowithdata.handler …
```

Return deployment status

---

pkg/utils/k8sutil.go

Don't be clever, just use the `URL.Hostname` function.
Related to #379

Use relevant URL function to find hostname

---

cmd/kubeless/autoscale.go
cmd/kubeless/autoscaleCreate.go
cmd/kubeless/autoscaleDelete.go
cmd/kubeless/autoscaleList.go
cmd/kubeless/call.go
cmd/kubeless/delete.go
cmd/kubeless/deploy.go
cmd/kubeless/describe.go
cmd/kubeless/ingress.go
cmd/kubeless/ingressCreate.go
cmd/kubeless/ingressDelete.go
cmd/kubeless/ingressList.go
cmd/kubeless/list.go
cmd/kubeless/logs.go
cmd/kubeless/update.go
pkg/utils/k8sutil.go

use the namespace set in current kubecfg context as default namespace instead of "default"

---

README.md

First time user will have difficulty when they run through installation steps and run into problem to bring Kafka pod up. Adding the requirement
that PV need to be provisioned in the installation steps.
Fixes #402

adding requirment for PV for kafka pod to be scheduled

---

pkg/utils/k8sutil.go

Continues #410
Avoid a possible race condition. If the same element is updated at the same time by two different sources one of the updates may be lost.
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#concurrency-control-and-consistency
cc/ @anguslees

Handle race condition while updating components

---

docs/runtimes.md
examples/Makefile
examples/python/helloget.py
kubeless-rbac.jsonnet
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go
tests/integration-tests.bats

**Issue Ref**: #436 
This PR limits the maximum amount of jobs kept in the history. It uses the default values of Kubernetes 1.8 (not present in Kubernetes 1.7). Apart from that the restart policy is now set to `Never` so it doesn't try to restart failed jobs and it also set the `ActiveDeadlineSeconds` to the function timeout so failed jobs doesn't exist more than the maximum execution time of the function.
It also adds a unit test and a integration test that this feature had missing. Also it fix the missing permissions for the controller for the RBAC (in which it hadn't permissions to manage CronJobs).
**TODOs**:

Add max number of jobs history

---

tests/integration-tests.bats

.NET end to end tests cause flaky builds since the lack of the `/healthz` endpoint. This PR disable these tests until #395 is fixed.
**TODOs**:
~~- [ ] Docs~~

Temporarily disable dotnet tests

---

cmd/kubeless/update.go
examples/Makefile
tests/integration-tests.bats

**Issue Ref**: Fixes #453
This PR adds the possibility of specifying the `--dependencies` flag for the `function update` command.
**TODOs**:

Add dependencies flag to update command

---

pkg/controller/controller.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: #399 
This PR discovers the API Version Group that the CronJobs are placed and uses it to do directly calls to the REST API.
**TODOs**:
~~- [ ] Docs~~ (Doesn't apply, bug fix)

Use REST API endpoint for CronJobs

---

cmd/kubeless/autoscaleCreate.go
cmd/kubeless/autoscaleList.go
cmd/kubeless/autoscaleList_test.go
cmd/kubeless/deploy.go
cmd/kubeless/function.go
cmd/kubeless/ingressCreate.go
cmd/kubeless/ingressList.go
cmd/kubeless/ingressList_test.go
pkg/controller/controller.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

This PR aims to add a label `created-by=kubeless` to all objects. Then it won't list out non-kubeless objects, specially for ingress and autoscale.
Fix #405

add label `created-by=kubeless` to all objects for filtering

---

kubeless-openshift.jsonnet
kubeless.jsonnet

**Issue Ref**: #480
The goal of this PR is fixing the Kafka deployment in Minikube (+v0.24). The feature `securityContext` doesn't work there and volumes are being created without write permissions for the user with id `1001`. In previous versions of Minikube volumes were mounted setting `777` as folder permissions  but it is not the case anymore. For fixing that this PR uses an initContainer that set enough permissions for the user `1001` to write in that volume. 
**TODOs**:
~~- [] Automated Tests~~ Minikube 0.24.X is not yet fully supported because of the autoscale feature. Tested Manually.
~~- [ ] Docs~~ Not needed, bug fix.

Use an init container instead of securityContext

---

cmd/kubeless-controller/kubeless-controller.go
cmd/kubeless/autoscaleCreate.go
cmd/kubeless/autoscaleDelete.go
cmd/kubeless/function.go
cmd/kubeless/function_test.go
kubeless-rbac.jsonnet
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/spec/spec.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

This PR moves the Horizontal Pod Autoscaler creation to the Kubeless controller. For doing so the Function spec now has an optional field `horizontalPodAutoscaler` that defines the autoscale properties if needed.
This is the first step for fixing the autoscale feature in Kubernetes 1.8
**TODOs**:
~~- [ ] Docs~~

Move HorizontalPodAutoscaler creation to the controller

---

docker/runtime/nodejs/event-trigger/kubeless.js
docker/runtime/nodejs/http-trigger/kubeless.js

**Issue Ref**: #484 
**Description**: Improves the metrics labels for nodejs http-trigger function's. Labels will be `function name-HTTP method`
**TODOs**:

Improve metrics labels for runtime nodejs http-trigger

---

examples/Makefile
script/libtest.bash
tests/integration-tests.bats

Due to #505 after deploying `pubsub-python*` examples the Kubernetes Node that host that function start running out of resources. This PR workaround it cleaning the environment after each test.
**TODOs**:
~~- [ ] Docs~~

Delete functions after verifying

---

docs/GKE-deployment.md
docs/misc/kafka-pv.yaml
docs/misc/zk-pv.yaml

**Description**:  On GKE 1.8.x, deploying Kubeless requires some more steps to create kafka and zookeeper PV. This PR add that step to the current guideline.
**TODOs**:

update GKE guideline for 1.8.x

---

.travis.yml
CONTRIBUTING.md
Makefile
script/cluster-up-minikube.sh
script/integration-tests
script/libtest.bash
tests/deployment-tests.bats
tests/integration-tests-kafka.bats
tests/integration-tests.bats

This PR organizes the `.travis.yml` file and its builds so by default only basic end-to-end tests are executed. If the build is related to Kafka (checking the PR title) it will launch the tests related to Kafka. If it is a build in `master` it will run all the tests.
**TODOs**:

Split Kafka tests in a different Travis build

---

cmd/kubeless/deploy.go

**Issue Ref**: [#443 ]
kubeless deploy command must validate if minimum required fields are sepcified. Else function deploy succeeds but controller fails toprovision resources for the function.
**TODOs**:

kubeless deploy command must validate if minimum required fields are sepcified.

---

docs/runtimes.md
pkg/langruntime/langruntime.go
pkg/langruntime/langruntime_test.go

#508 
It's possible to specify function runtime docker images via environment variables on the kubeless controller deployment. Runtime versions haven't been taken into account. This is now fixed.
**TODOs**:

fix GetFunctionImage from environment variable

---

cmd/kubeless/routeList.go

**Description**:
`kubeless route list` still uses the old table format.
```
$ kubeless route list
+------+-----------+------+------+--------------+--------------+
| NAME | NAMESPACE | HOST | PATH | SERVICE NAME | SERVICE PORT |
+------+-----------+------+------+--------------+--------------+
+------+-----------+------+------+--------------+--------------+
```
This PR updates routeList.go to have the table format consistent with other list commands (function list, autoscale list) 
**TODOs**:

update route display

---

chart/kubeless/templates/function-crd.yaml
chart/kubeless/templates/function-tpr.yaml
chart/kubeless/values.yaml

**Issue Ref**: [512](https://github.com/kubeless/kubeless/issues/512)
Helm chart was broken on k8s 1.8.
* Updated chart to use `CustomResourceDefinition`
* Image pulls were failing, updated tags to match [`kubeless-v0.3.1.yaml`](https://github.com/kubeless/kubeless/releases/download/v0.3.1/kubeless-v0.3.1.yaml)
**TODOs**:

Update Helm chart to use CRD

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go
examples/Makefile
pkg/langruntime/langruntime.go
pkg/langruntime/langruntime_test.go
pkg/spec/spec.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go
tests/integration-tests.bats

Add ServiceSpec to FunctionSpec so it can support creating Service with customizations.
ServiceSpec contains headless (boolean) and port (integer).
I have not updated the controller yet to take advantage of this, but want to run it by the reviewers first.

Add ServiceSpec to FunctionSpec

---

pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: #535 
v0.3.2 introduced a breaking change in function spec which leads to backward incompatibility with old versions. This PR set default serviceSpec if it doesn't present in function spec so old clients (serverless plugin, UI, kubectl) can work without issues.
**TODOs**:

use default svcSpec if it doesn't present in function spec

---

Makefile

`script/integartion-tests` need 2 arguments. The first one should be `minikube`. If it's omitted, there will be error below:
```
./script/integration-tests deployment
error: context "deployment" does not exist
FATAL: bringing up k8s cluster 'deployment' not supported
make: *** [Makefile:67: integration-tests] Error 255
make: *** [build_and_test] Error 2
```
**TODOs**:

minor fix to run script/integration-tests locally on minikube

---

.travis.yml

**Issue Ref**: None]
**Description**:  I am seeing travis upload multiple times when doing release because [this check](https://github.com/kubeless/kubeless/blob/master/.travis.yml#L144) is valid for all four jobs of the matrix. This leads to the mismatch of kubeless-controller digest between release manifest and the final one (can be verified via `script/find_digest.sh` script). 
This PR aims to do the upload once at the TEST_TARGET=minikube job. 
**TODOs**:
- [] ~~Automated Tests~~
- [] ~~Docs~~

upload once when doing the release

---

.travis.yml

Minkube and Minikube + Kafka scenarios where using `IMAGE_NAME:latest` as the controller image while `IMAGE_NAME:${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}` is the one being built.
**TODOs**:
~~- [ ] Docs~~

Fix Travis tests to use the correct image tag

---

kubeless-rbac.jsonnet
tests/integration-tests.bats

When using RBAC the controller cluster role didn't have permissions to manage monitoring resources causing errors and retries:
```
time="2018-01-10T11:17:42Z" level=error msg="Can't delete function: servicemonitors.monitoring.coreos.com \"tempv1\" is forbidden: User \"system:serviceaccount:kubeless:controller-acct\" cannot delete servicemonitors.monitoring.coreos.com in the namespace \"default\": Unknown user \"system:serviceaccount:kubeless:controller-acct\"" pkg=controller
```
To ensure a correct behavior, I added a test that checks that no error is found in the controller logs.
**TODOs**:
~~- [ ] Docs~~

Allow the controller to manage monitoring resources when RBAC is enabled

---

cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go

The previous approach build a `Function` object from scratch and obtained the default values from the `defaultFunction` parameter. That led to new properties like `HorizontalPodAutoscaler` to be deleted after updating the function. With the new approach it set the result to the `defaultFunction` and then overwrites it with the given values.
**TODOs**:
~~- [ ] Docs~~

Refactor update to properly use default values

---

examples/Makefile
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: Fixes #548
`wget` returns an error for some scheduled functions that are not present when using `curl` (see #548).
**TODOs**:
~~- [ ] Docs~~

Use curl instead of wget for triggering scheduled functions

---

README.md
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: Issue [559](https://github.com/kubeless/kubeless/issues/559)
**Description**: Service port name is changed to `http-function-port` 
**TODOs**:

Change service port name to use prefix http to support Istio

---

README.md
cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go

**Issue Ref**: [None]
**Description**: This pull request adds `--secret-names` argument to deploy and update commands. The secrets with given names will be mounted as Volumes inside pod with a Function. This is back port for version 0.3.x from [pull request 572](https://github.com/kubeless/kubeless/pull/572)
**TODOs**:

Secret cli 0.3.4

---

README.md

I changed the URL for the slack invite in the README. It now points to slack.k8s.io.

Changed Slack invite to new workspace

---

cmd/kubeless/function/function_test.go
cmd/kubeless/function/list_test.go
pkg/apis/kubeless/v1beta1/function.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/langruntime/langruntime.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

The changes for using `v1beta2` for deployments instead of `v1beta1` was incompatible with Kubernetes 1.7 which caused master builds to fail (in the GKE scenario). This PR goes back to use `v1beta1` which is compatible both with Kubernetes 1.7 and 1.8.
cc/ @ngtuna @sayanh
**TODOs**:
~~- [ ] Docs~~

Restore compatibility with Kubernetes 1.7

---

README.md
docs/README.md
docs/use-existing-kafka.md

**Issue Ref**: #196 #587 
This PR adds a document explaining how to deploy pubsub function with an existing Kafka cluster on the same Kubernetes cluster.
**TODOs**:

add a doc for existing kafka

---

.travis.yml

For unknown reason, the kafka-zookeeper manifest doesn't show up in the release package in previous PR #570. I guess I did something wrong with git squash and merge. This PR corrects it by adding proper kafka-zookeeper-${TRAVIS_TAG}.yaml file to the deploy job.
**TODOs**:

add kafka-zookeeper-${TRAVIS_TAG}.yaml to release

---

script/upload_release_notes.sh

Add a two liner to release note template so that people can copy/paste to get started on openshift.
points to `oc` command and openshift manifest.
**TODOs**:
- [ x] Ready to review
- [ N/A] Automated Tests
- [ x] Docs
We could add a build in travis to test on openshift...but this is just a template change.

add openshift special oc command to release notes

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/list_test.go
cmd/kubeless/function/update.go
docs/autoscaling.md

**Issue Ref**: #605
Adds `--cpu` argument to `function deploy` and `function update` to enable setting CPU limits, required for HPA.
**TODOs**:

Add CPU limit argument to function commands

---

.travis.yml
examples/Makefile
examples/python/hellowithdata34.py
script/libtest.bash

This PR adds integration tests for kafka trigger which is part of the trigger decoupling refactor. It's going to update the current kafka IT to 1) deploy kafka/zk/kafka-trigger-controller separately and 2) run through tests for pubsub funcs across supported languages.
I am going to step by step add commits to see travis result at each phase. So please don't review it now. I will call for review once it's in a good shape.
**TODOs**:

[WIP] Add integration tests for kafka trigger

---

pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: Fixes #634 
Init containers writes a file `func.sha256` that is being used to verify the integrity of the function deployed but it is using the volume mounted from the ConfigMap. After Kubernetes 1.9.4 this volume is mounted as read-only so the process fails trying to write that file.
**TODOs**:
~~- [ ] Docs~~

Avoid to write in ConfigMap volume

---

cmd/kubeless/route/routeCreate.go
pkg/apis/kubeless/v1beta1/http_trigger.go
pkg/utils/k8sutil.go

**Issue Ref**:  #638
Allows to specify the path of an ingress-enabled http trigger.
**PR Description**
Enhances the http trigger crd specification with the additional property `Path`:
````
type HTTPTriggerSpec struct {
FunctionName    string `json:"function-name"` // Name of the associated function
HostName        string `json:"host-name"`
TLSAcme         bool   `json:"tls"`
RouteName       string `json:"route-name"`
EnableIngress   bool   `json:"ingress-enabled"`
Path            string `json:"path"`
}
````
Creating via kubeless cli will set the path of an ingress enabled http trigger to the default "/" like before.
**TODOs**:

Path Definition for Ingress Enabled HTTP Triggers

---

kubeless-rbac.jsonnet
pkg/controller/cronjob_trigger_controller.go
pkg/controller/cronjob_trigger_controller_test.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go
script/libtest.bash
tests/integration-tests.bats

Minor refactor of the CronjobTrigger. It removes the `groupVersion` discovery that we were doing for supporting Kubernetes 1.7 and 1.9 which means that this PR will fail until the version 1.7 is deprecated.
Now when deleting a function, if it has a cronjobtrigger associated it will be deleted instead of just deleting the cronjob object.
It also includes unit/integration tests for checking that the trigger is removed when the function is deleted and that it properly detect changes in the cronjobtrigger.
**TODOs**:
~~- [ ] Docs~~

Minor refactor for cronjobtrigger. Add some tests

---

cmd/kubeless/trigger/http/create.go
cmd/kubeless/trigger/http/update.go
docs/http-triggers.md
pkg/apis/kubeless/v1beta1/http_trigger.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: #635
Enables basic authentication for kubeless HTTP Triggers.
Introduce new properties to the HTTP Trigger spec:
* basic-auth-secret
* gateway
**TODOs**:
- [x ] Ready to review
- [x ] Automated Tests

Basic Authentication Support for HTTP Triggers

---

cmd/kubeless/trigger/http/create.go
cmd/kubeless/trigger/http/update.go
docs/http-triggers.md
pkg/apis/kubeless/v1beta1/http_trigger.go
pkg/utils/k8sutil.go
script/libtest.bash
tests/integration-tests-http.bats

**Issue Ref**: https://github.com/kubeless/kubeless/issues/649
Fixes #649
This PR provides an option for function user to use existing certificate for TLS igress.
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
**TODOs**:

HTTP trigger: TLS with existing certificates

---

examples/Makefile
script/libtest.bash

Fixes two spurious errors that appears sometimes in the CI:
1. It is trying to get the python dependencies while there are two pods for the function:
```
not ok 6 Test function update: get-python-deps
...
...
```
2. It is trying to deploy a function when it has not been deleted yet:
```
not ok 5 Create HTTP Trigger with basic auth
...
```
**TODOs**:
~~- [ ] Docs~~

Fix spurious errors in CI

---

pkg/langruntime/langruntime.go
pkg/langruntime/langruntime_test.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: Fixes #623
This PR includes two fixes:
- When processing a Deployment use PATCH instead of PUT and avoid deleting existing pods. This causes rolling updates to work properly and avoid unnecessary pod restarts. We should also avoid to modify the `Deployment.Spec.Selector` to generate a different ReplicaSet and let the previous one orphaned (and running).
- When processing a Service update including new Labels avoid changing the Selector to avoid downtime while the new Pods with the new labels are being started.
* Extra: I added a checksum validation for function dependencies so that triggers a new rolling update when only the dependencies get updated
cc/ @sayanh 
**TODOs**:
~~- [ ] Docs~~

Avoid downtime when updating functions

---

.travis.yml
script/upload_release_notes.sh

This PR fixes:
- `.travis.yaml`: The tag of the image `function-image-builder` was wrongly set to the SHA of the controller. To avoid that all the images uses the tag of the release e.g. v0.6.0
- `upload_release_notes.sh`: [Fixed unescaped line](https://travis-ci.org/kubeless/kubeless/jobs/367642931#L1954). Increased reliability using authentication in all the API calls. 
**TODOs**:
~~- [ ] Docs~~

Fix release issues

---

docs/quick-start.md

The URL format when using the proxy has changed (https://github.com/kubernetes/kubernetes/pull/59884/files). This updates the quickstart guide to match.
This structure has been in place since v1.3. v1.10 removed it.

Update Proxy URL format for k8s v1.10

---

docker/runtime/golang/Dockerfile.init
docker/runtime/php/Dockerfile
kubeless-non-rbac.jsonnet
kubeless-openshift.jsonnet
pkg/langruntime/langruntime.go
pkg/langruntime/langruntime_test.go

**Issue Ref**: Fixes #694
OpenShift doesn't allow to use the UID 1000 and uses by default a different one. That causes permissions issues for NodeJS, Go, and PHP. See context at #694.
**TODOs**:
~~- [ ] Docs~~

Fix Openshift permission issues

---

docs/architecture.md

this pr aim to use some kubernetes terms exchange unstandard terms in docs/architecture.md. Make it easy to read.Some reader who don't understand terms like configmap or apiserver can easily using google to search the related infomation.

change some terms in architecture.md

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go

I notice image-poll-policy of the pod created by kubeless is always.we should let user choose their image-pull-policy, Including (IfNotPresent,Never,Always).

<cmd/function>: make user be able to choose image-pull-policy

---

docker/runtime/golang/kubeless.tpl.go
docker/runtime/nodejs/kubeless.js
docker/runtime/php/Controller.php
docs/kubeless-functions.md
kubeless-non-rbac.jsonnet
pkg/functions/params.go

**Issue Ref**: Fixes #712
Add response object to `event.extensions`. It allows function to customize response properties like the status code or headers.
It is not necessary to perform any change for Python and Ruby since it is already possible to return a `response` object for those frameworks.
**TODOs**:

Add response object to function event

---

docker/runtime/golang/Dockerfile
kubeless-non-rbac.jsonnet

**Issue Ref**: Fixes #748 
Add ca-certificates for Golang runtime image.
**TODOs**:
~~- [ ] Docs~~

Add ca-certificates to Golang runtime image

---

docs/dev-guide.md

section `### Building k8s manifests file` is missing a `cd` before the `make all-yaml` command.
**Issue Ref**: N/A
Simple doc update for the dev build build. I believe I'm following the directions properly and end up with a `$GOPATH/src/github.com/kubeless/kubeless` directory in which the kubeless repo is cloned, in that case we need to cd into it before running any `make` commands.
Looking at the other make commands (like `make binary-cross`) it appears this is the expected directory structure.
Caveat: my first go project.
**TODOs**:

Add missing `cd` command to dev guide

---

docker/runtime/nodejs/Dockerfile.6
docker/runtime/nodejs/Dockerfile.8.opt
docker/runtime/nodejs/kubeless.js
docs/runtimes.md
examples/Makefile
kubeless-non-rbac.jsonnet
tests/integration-tests.bats

**Issue Ref**:  #750 
Provide a bare minimum docker image for nodejs using distroless.
An additional Dockerfile Dockerfile.8.opt is added which provides a bare minimum nodejs 8 runtime using the distroless images.
One refactoring is required. All kubeless related files need to be put within a sub folder.
This affects all nodejs dockerfiles and the kubeless.js file.
Currently, this sub folder is named <b>kubeless_rt</b>.
Before, in example the lib folder has been copied to the root directory and conflicts with an existing folder within the distroless base image.
I have tested the refactored nodejs docker images Dockerfile.8 and Dockerfile.8.opt.
The additional image is not yet integrated in the overall make/build process.
**TODOs**:

Nodejs Runtime: Use bare minimum base image

---

docs/runtimes.md
pkg/controller/function_controller_test.go
pkg/langruntime/langruntime.go
pkg/langruntime/langruntime_test.go
pkg/langruntime/langruntimetestutils.go
pkg/utils/kubelessutil.go

**Issue Ref**: [#760]
This PR allows user to override default `httpGet` health checks. This is necessary for the case when we are using kubeless with Istio. Where `httpGet` based health checks are not possible. 
**TODOs**:

760 make healthcheck configurable

---

pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

**Issue Ref**: Fixes #810
Avoid to overwrite a resource if it doesn't contain the label `created-by: kubeless`. Ensure that all the resources created by kubeless contain that label.
**TODOs**:
~~- [ ] Docs~~

Avoid to overwrite existing resources

---

docs/use-existing-kafka.md
pkg/event-consumers/kafka/kafka-consumer.go
pkg/event-consumers/kafka/utils.go
pkg/event-consumers/kafka/utils_test.go

**Description**: Add TLS and SASL configuration for existing kafka clusters.
When using existing kafka cluster, you might want to integrate it with SASL/SSL configuration. This PR make this possible.
**TODOs**:

Add TLS & SASL configuration for existing kafka brokers

---

cmd/kubeless/function/function.go
cmd/kubeless/function/top.go
cmd/kubeless/function/top_test.go
examples/Makefile
pkg/utils/event_sender.go
pkg/utils/metrics.go

**Issue Ref**: 
Fixes #375 
Added the `top` (`stats` can also be used) command to the kubeless CLI for retrieving function statistics from Prometheus.
```
kubeless function top 
kubeless function stats --function get-python --namespace default --out json
```
**TODOs**:

Show function statistics in CLI

---

docker/runtime/nodejs/kubeless.js
docs/runtimes.md
kubeless-non-rbac.jsonnet

**Issue Ref**: Fixes #818
Make the maximum size for the payloads received with the env var `REQ_MB_LIMIT`.
cc/ @cscheiber
**TODOs**:

Nodejs: make maximum request size configurable

---

cmd/kubeless/function/describe.go

None 
bug fix : kubeless function describe will panic when Containers are empty.
This happened when function is created by kubeless-ui.
```go
func print(f kubelessApi.Function, name, output string) error {
...
env, err := json.Marshal(f.Spec.Deployment.Spec.Template.Spec.Containers[0].Env)
```
The function is 
```yaml
$ kubectl get function xxx -o yaml
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
clusterName: ""
creationTimestamp: 2018-06-29T06:59:34Z
finalizers:
- kubeless.io/function
generation: 1
name: xxx
namespace: default
resourceVersion: "872425"
selfLink: /apis/kubeless.io/v1beta1/namespaces/default/functions/xxx
uid: fabbed3a-7b69-11e8-8251-6c0b84ace257
spec:
checksum: …
```

kubeless function describe panic

---

examples/ruby/function.yaml

Is a need for volunteers on this project?  I think it's something I would use, maybe someone can throw out some ideas for what else is needed in terms of updating docs or other things that a new contributor could helpfully tackle.
Was the API `apiVersion: k8s.io/v1` intentional?  I don't know if kubeless is intended to be upstreamed into k8s.io but function does not seem to be in my `k8s.io/v1` as of the latest minikube.
(Also, thanks for the mostly working example!)
I had to make a couple of changes to this example to get it to work, but this version worked.
Submitted for your consideration
**TODOs**:

Ruby example is wrong or outdated

---

.circleci/config.yml
docs/GKE-deployment.md

This is the oldest version supported on GKE now, I think
(1.8.10-gke.0)
**TODOs**:

Fix GKE build for CircleCI

---

.circleci/config.yml
README.md

Using Kubernetes 1.8 now in GKE throws a warning. They have moved the default version to 1.9 so we can stop using 1.8 in our CI for GKE. Next step would be to start testing in 1.10.
**TODOs**:

Update K8s GKE version

---

script/binary-cli

I don't think we need 386 client build anymore

remove 386 from the build

---

docker/runtime/python/Dockerfile.3.6
examples/Makefile
examples/python/hellowithdeps.py
examples/python/hellowithdepshelper.py
pkg/langruntime/langruntime.go
pkg/utils/kubelessutil_test.go

**Issue Ref**: Fixes https://github.com/kubeless/kubeless/issues/860 and #590
~Adding `PYTHONPATH` environment variable so python files can import other python files.~ The current setup is broken because the python program is not run from the directory of the project files. Adding the mount directory to the python path should alleviate this problem
EDIT: Extending the `PYTHONPATH` variable to also include the mount point for the assets
As a failing test case, I made `examples/python/hellowithdeps.py` pull it's implementation of foo from a local file, as such I needed to make the deploy function send up a zip with both files instead of just the single python file. Before, this would fail with `hellowithdepshelper not found`, the modified test demonstrates it passing. …

BUGFIX: Extending PYTHONPATH to fix local imports

---

docs/function-controller-configuration.md
kafka-zookeeper.jsonnet
kubeless-non-rbac.jsonnet
pkg/controller/function_controller.go

**Issue Ref**: Fixes #829 #867
Allow administrators to set the config property "functions-namespace" for the controller to listen in a specific namespace. This PR also include docs to explain how to install different instances of Kubeless in the same cluster.
**TODOs**:

Support several instances of Kubeless per cluster

---

docs/function-controller-configuration.md
docs/implementing-new-trigger.md
docs/use-existing-kafka.md
kafka-zookeeper.jsonnet
kubeless-non-rbac.jsonnet

**Issue Ref**: Fixes  #881
In K8s 1.11 the `Description` field is not available.
**TODOs**:

Remove description for CRDs

---

docs/use-existing-kafka.md

**Issue Ref**: 
None
The final code block section in https://kubeless.io/docs/use-existing-kafka/ is missing a leading newline, which prevented the block being formatted as a code block. This PR adds that new line to fix the formatting issue on the page.
**TODOs**:

Fix formatting issue in use-existing-kafka.md

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/update.go
examples/Makefile

**Issue Ref**: Fixes #824
Cobra's `StringArray` doesn't behave as expected. `StringSlice` should be used instead.
**TODOs**:
~~- [ ] Docs~~

Fix --env flag for arrays

---

examples/golang/Gopkg.toml
pkg/langruntime/langruntime.go

**Issue Ref**: Fixes #911
For the Golang runtime, remove the vendored `kubeless` folder if exists. More info at #911.
**TODOs**:
~~- [ ] Docs~~

Remove necessary ignore for Gopkg files

---

docker/runtime/python/kubeless.py
kubeless-non-rbac.jsonnet

Hello,
**Issue Ref**: This is proposal to make function routing handling consistent
Node.js and other runtimes listen to wildcard route. Python is exception 
this is how wildcard route is defined in the Bottle framework `'/<:re:.*>'`
https://github.com/bottlepy/bottle/issues/178

Python wildcard route support

---

examples/Makefile

`kubectl logs` (+v1.13) reduces the result to ten lines when using a selector (`-l`). This affect our tests. 
**TODOs**:
~~- [ ] Docs~~

Increase logs size in examples checking

---

pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

**Issue Ref**: Fixes #986 
Fixes getFileName function to infer file suffix for base64 encoded functions.
**TODOs**:
~~- [ ] Docs~~

Fixes evaluation of the file suffix for functions with base64 content type

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go
pkg/utils/kubelessutil.go

**Description**: After updating runtime images to use non-root user it is become impossible to run functions on port 80. To fix this `Service` can map port 80 to target port 8080. To support this this pull request was prepared. Also another one will come to `serverless-kubeless` plugin.
**TODOs**:

differentiate service port and target port for container

---

cmd/kubeless/function/deploy.go

https://github.com/kubeless/kubeless/issues/989
In RBAC-restricted cluster user might have no permissions to see cluster-scoped things
I was not sure whether you still want to leave the warning and do that check.
**TODOs**:

Disable runtime check if has no permissions to do so

---

.circleci/config.yml
cmd/kubeless/trigger/http/create.go
docs/http-triggers.md
script/start-test-environment.sh
vendor/github.com/kubeless/http-trigger/pkg/apis/kubeless/v1beta1/http_trigger.go
vendor/github.com/kubeless/http-trigger/pkg/utils/k8sutil.go

934
Support for CORS for HTTP endpoints is expected here. This pull request provides cors flag while creating HTTP trigger.
cors flag has been added to below command
kubeless trigger http create
cors-enable flag is a boolean flag, by default it is false to be backward compatible.
if cors-enable flag is true, then one can specify cors-domain  which will set that only for this cors-domain, cors will be enabled.
Tests have been added to http-trigger repo.
**TODOs**:

Add CORS support

---

pkg/langruntime/langruntime.go
pkg/utils/kubelessutil.go

Container env variable array was not passed to Compile Container method. This made all those environment variable missing in Compile container phase
This is for issue 972
**Issue Ref**: 972
**Description**: Container env variable array was not passed to Compile Container method. This made all those environment variable missing in Compile container phase
[PR Description]:Pass environment variables to compile phase of a Java function container

Passing Container env variables to Compile container

---

README.md

Quick typo/missing word fix in the README:
```diff
- A UI available
+ A UI is available
```
**TODOs**:

README - quick typo fix

---

docs/runtimes.md

**Issue Ref**: kubeless/runtimes#45
**Description**:
Information about usage of `nuget.config` is not readily available in the documentation and this PR aims to solve that issue.
Although this can be discovered through experimentation after finding out that using zip files is possible (which I discovered after seeing the REST API example in the functions repository), I believe it would be more beneficial to include it in the documentation.
**TODOs**:

Include information about nuget.config in .NET Core documentation

---

cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/list_test.go
cmd/kubeless/function/top_test.go
pkg/apis/kubeless/v1beta1/function.go
pkg/controller/function_controller.go
pkg/controller/function_controller_test.go
pkg/langruntime/langruntime.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go
pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

**Issue Ref**: #1086 
Use apps/v1 endpoint instead of the deprecated extensions/v1beta1.
**TODOs**:
~~- [ ] Docs~~

Use new apps/v1 endpoint

---

pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: [#1035]
Manually merge VolumeMounts in runtime container if defined in configmap.
[Mergo](https://github.com/imdario/mergo) doesn't add the VolumeMounts https://github.com/kubeless/kubeless/blob/master/pkg/utils/k8sutil.go#L376
possibly due to this error
```
cannot use deployment.Spec.Template.Spec.Containers[0].VolumeMounts (type []"k8s.io/api/core/v1".VolumeMount) as type "k8s.io/api/core/v1".VolumeMount in append
```
**TODOs**:

fixes bug so that configmap volumemounts are merged in deployment

---

pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

**Issue Ref**: Fixes #1092
Quote the URL when using the type `url` to avoid interpreting characters like `&`.
**TODOs**:

Quote curl URL

---

docs/function-controller-configuration.md
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: #1113 @andresmgot 
Merge container values when merging the deployment template config to allow specifying things like resources, labels, annotations, etc for containers.
**TODOs**:
I just added a resource value in the documented example to suggest to readers that this is possible. Let me know if I should explicitly mention it somewhere.

Merge deployment containers as well

---

docs/advanced-function-deployment.md
pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

Adds a soft pod anti affinity rule to function deployments so that, where possible, function pods are deployed to different nodes.
Being only a soft or "PreferredDuringSchedulingIgnoredDuringExecution" anti affinity rule it remains backwards compatible because if the rule can't be satisfied it'll fall back to the current behavior.
Some reading for those unfamiliar: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity
**TODOs**:
I'm unsure if this needs to be documented anywhere, point me in the right direction if it should be.

Add soft pod anti affinity

---

pkg/controller/function_controller.go
pkg/utils/k8sutil.go
pkg/utils/k8sutil_test.go

**Issue Ref**: #1116 
If the creation of a HPA returns an error becasue one with that name already exists, then perform an update.
This prevents the error triggering a retry up to the retry limit and slowing down queue consumption.
**TODOs**:

If HPA already exists, perform an update.

---

docs/runtimes.md

**Issue Ref**: https://github.com/kubeless/runtimes/pull/71
Updates documentation for golang functions to reflect usage of go modules for dependency management. This is a breaking change update for go functions.
**TODOs**:

Update golang docs

---

examples/Makefile

https://github.com/kubeless/runtimes/pull/71 intorduces BC breaking change by removing runtimes `go1.10`, `go1.11` and `go1.12`, which broke the integration tests using runtime `go1.10`. This PR updates the Go test runtime to `go1.14`.
**TODOs**:

Use runtime go1.14 in integration tests

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go
examples/Makefile

**Issue Ref**: #1156 
Add a new option `--node-selectors` to the `kubeless function deploy` and `kubeless function update` commands to specify node-selectors for the function.
**TODOs**:

kubeless function deploy/update: add option to specify node selectors.

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/update.go

**Issue Ref**: #1160 
The `kubeless function ls` command which is displayed at the end of function deploy/update should include the namespace argument (if any) without which the command does not display any functions.
**TODOs**:

Display function list command with namespace argument after deploy/update

---

cmd/kubeless/function/deploy.go
cmd/kubeless/function/function.go
cmd/kubeless/function/function_test.go
cmd/kubeless/function/update.go

**Issue Ref**: [1162](https://github.com/kubeless/kubeless/issues/1162)
Added --service-account option for function deployment or update. 
```
kubeless function deploy hellogo --namespace kubeless --runtime go1.12 --from-file helloget.go --handler helloget.Foo --service-account controller-acct
```
```
kubeless function update hellogo --namespace kubeless --runtime go1.12 --from-file helloget.go --handler helloget.Foo --service-account default
```
**TODOs**:

Added "--service-account" option for function deployment or update

---

docs/function-controller-configuration.md
pkg/controller/function_controller.go
pkg/langruntime/langruntime.go
pkg/langruntime/langruntimetestutils.go
pkg/utils/k8sutil.go
pkg/utils/kubelessutil.go
pkg/utils/kubelessutil_test.go

Adds support for using secrets via mounted volumes.
Extends the `runtime-images` structure in `kubeless-config` configmap to allow using secrets in the init containers of function deployments, in a similar way as providing environment variables.
**Usage:**
Manifest for `github-token` secret.
```yaml
apiVersion: v1
kind: Secret
metadata:
name: github-token
type: Opaque
stringData:
token: foobar
```
Manifest for `kubeless-config` configmap
```yaml
...
data:
runtime-images: |
[
{
"ID": "go",
"depName": "go.mod",
"fileNameSuffix": ".go",
"versions": [
{
"imagePullSecrets": [{"ImageSecret": "docker-registry"}],
"images": [
{
"command": "docker-entrypoint",
"env": {
"GITHUB_TOKEN_SECRET_FILE": "/var/run/secrets/kubeless.io/github-token/token",
"GOCACHE": …
```

Add secrets to runtime configuration

---

docker/dev-environment/Dockerfile
docker/event-sources/kubernetes/Dockerfile

**Issue Ref**: [None]
optimize the git clone using --depth flag in term of size of clone
and also in term's of time taken to fetch the files and commit history
of whole repository .
More detail can be found at blog
https://www.atlassian.com/git/tutorials/big-repositories
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

Use `--depth` flag to `git clone` in Dockerfiles, to save space

---

docker/event-sources/kubernetes/Dockerfile

**Issue Ref**: [None]
using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

use `--no-cache-dir` flag to `pip` in dockerfiles to save space

---

pkg/utils/kubelessutil.go

**Issue Ref**: 
[1211](https://github.com/kubeless/kubeless/issues/1211)
With this PR the function deployment uses only 'function' and 'created-by' labels as matchLabels instead of all the function labels.
This PR is really simple but i couldn't test if it works correctly.
Thank you for your great work!
Lorenzo
**TODOs**:

Use only 'function' and 'created-by' labels as deployment matchLabels

---

cmd/kubeless/function/call.go

**Issue Ref**: https://github.com/kubeless/kubeless/issues/1226
First of all, thank you for the exciting project.
My kubeless is running on Kubernetes 1.21.
As a result of creating a function according to Quick Start (https://kubeless.io/docs/quick-start/), I confirmed that the function cannot be called with `kubeless function call` like https://github.com/kubeless/kubeless/issues/1226.
However, when I checked the function using `kubectl proxy` and` curl`, it was working properly.
So I guessed that there was a problem with the assembled URL in the command.
When I checked the assembled URL, it was as follows.
```
https://kubernetes/:http-function-port/proxy/
```
I fixed `svc.ObjectMeta.SelfLink` and` svc.SelfLink` to not be used because they were empty.
Then, I have …

Fix broken URL in kubeless function call
