docker/events/event-consumer/kubeless.py, examples/Makefile, examples/python/pubsub.py
fix about json decoding in kafka consumer
plus small tweaks in Makefile to run examples.
=> fix for json decoding in pubsub

docker/runtime/python-2.7/kubeless.py
we need a helathz route to get ingress healthcheck working on GKE
=> add healthz route

docker/events/event-consumer/kubeless.py, examples/python/pubsub.py
to be able to deal with text messages
=> add safe deserializer to kafka consumer

examples/slack/Makefile, examples/slack/README.md, examples/slack/bot.py, examples/slack/requirements.txt
Example to send a message to SLACK with a `--trigger-http` function
=> Add SLACK example

examples/minio/slack/README.md, examples/minio/slack/bot.py, examples/minio/slack/requirements.txt, examples/slack/bot.py
Add a function that's triggered on minio bucket events.
=> Slackpubsub

README.md, cmd/kubeless-controller/kubeless-controller.go, cmd/kubeless/call.go, cmd/kubeless/create.go, cmd/kubeless/delete.go, cmd/kubeless/install.go, cmd/kubeless/list.go, cmd/kubeless/logs.go, cmd/kubeless/topicCreate.go, cmd/kubeless/version.go, glide.yaml, pkg/controller/controller.go, pkg/controller/function_resource.go, pkg/function/function.go, pkg/utils/k8sutil.go, script/.build, script/.validate, script/binary, script/binary-cross, script/make.sh
skippbox/kubeless -> bitnami/kubeless
=> change import urls to bitnami/kubeless

docker/controller/Dockerfile
Tested by building a new image and creating a function using it.
Closes #75
=> Move the controller image to minideb

README.md, cmd/kubeless/create.go, cmd/kubeless/function.go, examples/Makefile, examples/minio/README.md, examples/minio/slack/README.md, examples/slack/Makefile, examples/twitter/README.md
`$ kubeless function deploy`
ref: #55
=> function create -> function deploy

docker/events/event-consumer/kubeless.py, examples/minio/README.md, examples/minio/minio-test.py, examples/minio/slack/bot.py, examples/twitter/README.md, examples/twitter/requirements.txt
=> add consumer group and fix slack example

cmd/kubeless/list.go, pkg/controller/controller.go, pkg/utils/k8sutil.go
Solving the problem of having multiple functions with same name but in different namespaces.
=> fix namespace mess up issue, ref: #5

docs/dev-guide.md
I added the dev guide for people getting on board to the project and start collaborating.
=> add development guide

.travis.yml, script/binary
- Build/test on both linux + osx
- Build/test using go 1.8 as well
- Run all the validation tools, even if one fails
- Build release zip using existing binary-cross script
=> travis.yml improvements

pkg/utils/k8sutil.go
=> scale deployment to 0 and then delete it

README.md
I used HTML code to center the image in the README.
=> Add the Kubeless logo to the README file

cmd/kubeless/topicCreate.go, cmd/kubeless/topicDelete.go, cmd/kubeless/topicList.go, pkg/utils/k8sutil.go
Kafka and zookeeper locating in a single pod, so that makes sense to have kafka connecting to zookeeper via localhost:2181 instead of calling zookeeper service.
=> make kafka connect zookeeper via localhost

README.md
This just adds some info which I was looking for when doing a tutorial on kubeless.
Thanks!
=> Add an example curl for http README example.

pkg/utils/k8sutil.go
This is a hot fix to have init container running in the case of pubsub function with dependency file. This case was running very well with the old k8s client but when I turned to use client-go this becomes a known bug. Reference issue: https://github.com/kubernetes/client-go/issues/142
=> able to run init container with client-go

pkg/utils/k8sutil.go
I would like to temporarily remove the liveness probe check for pubsub function while we haven't figured out a good solution for adding it. This might harm the `function update` for pubsub a bit but it's just for a quick release next week. Please consider to add it to master or if you have great idea plz raise it up I will be happy to update the PR.
=> temporary remove liveness probe check for pubsub func

manifests/ui/ui-deployment.yaml, manifests/ui/ui-svc.yaml
Start of a basic manifest to run the UI.
UI runs but there are proxy issues, need to check with @kemcake
=> deployment manifests for running the UI

manifests/ui/ui-deployment.yaml
this is the version of the UI that works in-cluster
=> add development tag to UI image

manifests/kafka/kafka-stateful.yaml, manifests/zookeeper/zk-stateful.yaml, pkg/utils/k8sutil.go
=> Update kafkazk stateful

pkg/controller/controller.go
This PR aims to fix the controller hanging issue which happens sometimes. Ref issue #117 
My idea is trying to keep the loop running all the time and bypass errors might have (of course they are logged). This is still under testing so don't merge it until we are confident with tests.
=> restructure the controller loop

README.md
seems it is already deployed using statefulset
=> Update readme about kafka,zookeeper statefulset

README.md, docs/release-flow.md
=> Add release doc

kubeless.jsonnet
=> update tpr version to v1

pkg/utils/k8sutil.go
As request from Seb, I update the liveness probe period to 30s. cc/ @anguslees
=> update liveness probe period to 30s

cmd/kubeless/topicCreate.go
=> cli: improve error message when kafka pod is not found

docker/runtime/ruby-2.4/http-trigger/Dockerfile, docker/runtime/ruby-2.4/http-trigger/build.sh
It fixes #209 and do not install ruby doc
=> fixes #209

pkg/utils/k8sutil.go
Follow up PR #202 : updating digests for python-2.7 runtime images.
cc/ @sebgoa
=> update digests for python runtimes

pkg/utils/k8sutil.go
I update this to use Patch() http request with type:
```
StrategicMergePatchType PatchType = "application/strategic-merge-patch+json"
```
cc/ @anguslees @sebgoa
=> change Update() to Patch() request for function update

.travis.yml, Makefile, kubeless-rbac.jsonnet, kubeless.jsonnet
Fix RBAC:
- kubeless.jsonnet:
(always) deploy controller with specific system:serviceaccount:kubeless:controller-acct
- kubeless-rbac.jsonnet:
on top of above, add role and binding to serviceaccount
=> [jjo] fix RBAC #191

kubeless.jsonnet
the labels for the services were wrong
=> fix labels in services for kafka and zookeeper selectors

docker/runtime/python-2.7/event-trigger/kubeless.py, docker/runtime/python-3.4/event-trigger/kubeless.py
cc/ @sebgoa 
This PR fixes #226 where there is a parenthesis missing for kafka_server variable
=> add parenthesis to string format

helm/kubeless/Chart.yaml, helm/kubeless/templates/kafka-stateful.yaml, helm/kubeless/templates/zk-stateful.yaml, helm/kubeless/values.yaml, manifests/kafka/kafka-stateful.yaml, manifests/zookeeper/zk-stateful.yaml
- the latest versions are non-root
=> chart/manifest: update zookeeper and kafka

.travis.yml, Makefile, kubeless-openshift.jsonnet, kubeless.jsonnet
- also updates zookeeper and kafka to the latest non-root versions
=> add openshift ksonnet manifest

cmd/kubeless/ingress.go, cmd/kubeless/ingressCreate.go, cmd/kubeless/ingressDelete.go, cmd/kubeless/ingressList.go, cmd/kubeless/ingressList_test.go, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go
Re-submit PR for ingress. I updated `--domain` to `--hostname`. cc/ @anguslees @sebgoa
=> enable ingress route to function

cmd/kubeless/deploy.go, cmd/kubeless/list.go, cmd/kubeless/list_test.go, examples/Makefile, pkg/utils/k8sutil.go
appending an empty initContainer causes error `[spec.template.spec.initContainers[0].name: Required value`
=> validate initContainer before appending

script/integration-tests
Carry bats exit_code towards integration-tests exit.
=> [jjo] fix integration-tests exit code

docker/runtime/ruby-2.4/http-trigger/build.sh, pkg/utils/k8sutil.go
When fixing #212 the image reference was not updated. I builded the image and pushed it.
=> Change ruby image reference

script/binary-cli
Compile kubeless cli for windows (386 and 64)
=> provide windows cli

README.md, docs/architecture.md, examples/minio/README.md, examples/minio/slack/requirements.txt, examples/nodejs/function.yaml, examples/slack/Makefile, examples/twitter/README.md
after the change of runtime version we did not properly cleanup
=> fix runtime version

README.md
* Cosmetic changes for markdownlint. 
* Output from commands.
* Two extra commands for clarification
* Background the proxy
=> Cosmetic changes for markdownlint. More output.

.travis.yml, kubeless.jsonnet
Every time we run integration test, we need to update controller image to newest. I tag it as _test_ and update its sha256 to the yaml file.
=> update controller image for integration test

examples/Makefile, examples/ruby/Gemfile, examples/ruby/hellowithdeps.rb, pkg/utils/k8sutil.go, tests/integration-tests.bats
Updates the controller to insert an init container for Ruby runtimes
when a Gemfile is provided. Bundler is set to install gems in the shared
volume and GEM_HOME is set in the container to load the gems from this
volume.
=> install ruby gem dependencies

README.md
When setting up and building the project I found that it would have been easier with a few additional tips on how the makefile is used.
=> Small improvements to README 

pkg/utils/k8sutil.go
fix #294 
cc/ @anguslees @sebgoa
=> inject envvar to initcontainer as well

examples/Makefile, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go
This PR adds support for the python3.4 runtime.
Fixes #301
=> Add python3.4 image

docs/debugging.md, docs/dev-guide.md, docs/implementing-new-runtime.md, docs/kubeless-on-azure-container-services.md
Adding new docs for:
- debugging.md (explains how to debug kubeless code using VS Code)
- dev-guide.md (updated for general setup to build local binaries + scripting for automatization tasks)
- kubeless-on-azure-container-services.md (general explanation about how use kubeless on ACS)
- implementing-new-runtime.md (general guide to implement new language runtime for kubeless)
Referencing #305
=> Docs improvement

examples/minio/requirements.txt
=> solve miguel's bug

examples/minio/README.md, examples/minio/slack/README.md
=> Improve Minio examples documentation

.gitignore, CONTRIBUTING.md, README.md, docs/dev-guide.md, docs/index.md
This PR intends to add the contributing documentation (`CONTRIBUTING.md`) and a structured view of the documentation (`doc/index.md`)
Fix #317
=> Adding contributing documentation

CONTRIBUTING.md
The link to the developer's guide
=> Fixed broken link in CONTRIBUTING.md

CONTRIBUTING.md, OWNERS
Had owners file and edit a bit the contributing.md file
=> owners files

docs/ingress.md
=> docs: ingress: update links

.gitignore, .travis.yml, Makefile, docs/architecture.md, docs/dev-guide.md, script/binary, script/binary-cli, script/binary-controller, script/cluster-up-dind.sh, script/cluster-up-minikube.sh, script/find_digest.sh, script/integration-tests, script/kubeless_uninstall.sh, script/libtest.bash, script/validate-lint, script/validate-test, script/validate-vet
This PR intends to factorize the build and test environment setup. Changes were made to:
* Allow running more easily on MacOSX
* Use canonical shebang for scripts which allow to be more resilient to custom environments
* Add a single make target to bootstrap the tools needed for development and automated build
* Add missing repo folder descriptions
=> Development setup enhancements

Makefile, docs/dev-guide.md, script/libtest.bash
Adressed some comments from @anguslees in previous related PR.
* Simpler bootstrap target
* fixed typo
* remove shebang in library script
=> Simplified bootstrap Makefile target

README.md, docs/README.md, docs/ingress.md, docs/troubleshooting.md
This PR intends to enhance the first experience by 
* Correcting some of the examples
* Adding additional information for some examples
* Introducing a troubleshooting guide
=> First experience enhancements

kubeless.jsonnet, script/libtest.bash, tests/integration-tests.bats
=> Enable topic deletion.   Fixes #389

README.md, cmd/kubeless/deploy.go, examples/api/README.md, examples/api/api/controllers/todoListController.js, examples/api/api/models/todoListModel.js, examples/api/package.json, examples/api/server.js
Example demonstrating how to deploy a function composed by several functions.
It also includes some updates to the main documentation.
=> Multi file example

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Add a PR template for further PRs.
**TODOs**:
=> Add template for PRs

cmd/kubeless/deploy.go, cmd/kubeless/update.go, glide.lock, glide.yaml, pkg/langruntime/langruntime.go, vendor/github.com/robfig/cron/.gitignore, vendor/github.com/robfig/cron/.travis.yml, vendor/github.com/robfig/cron/LICENSE, vendor/github.com/robfig/cron/README.md, vendor/github.com/robfig/cron/constantdelay.go, vendor/github.com/robfig/cron/constantdelay_test.go, vendor/github.com/robfig/cron/cron.go, vendor/github.com/robfig/cron/cron_test.go, vendor/github.com/robfig/cron/doc.go, vendor/github.com/robfig/cron/parser.go, vendor/github.com/robfig/cron/parser_test.go, vendor/github.com/robfig/cron/spec.go, vendor/github.com/robfig/cron/spec_test.go, vendor/github.com/sirupsen/logrus/README.md, vendor/github.com/spf13/cobra/README.md, vendor/github.com/spf13/cobra/command.go, vendor/github.com/spf13/cobra/command_test.go
=> perform input validation for kubeless deploy and update subcommads

README.md, cmd/kubeless/deploy.go, cmd/kubeless/function.go
=> Modify default trigger to be --trigger-http

cmd/kubeless/call.go, docker/runtime/python-2.7/event-trigger/kubeless.py, docker/runtime/python-2.7/http-trigger/kubeless.py, docker/runtime/python-3.4/event-trigger/kubeless.py, docker/runtime/python-3.4/http-trigger/kubeless.py, examples/Makefile, pkg/langruntime/langruntime.go, pkg/utils/k8sutil_test.go, tests/integration-tests.bats
Issue Ref: #365 
Summary:
This PR adds a timeout handler for the Python runtime. If a function takes more than 3 seconds on its execution the subprocess get killed. The timeout is configurable using the environment variable FUNC_TIMEOUT.
Also, to avoid duplicated `kubeless.py` files (from python-2.7 and python-3.4 folders) they are now hard links.
TODOs:
=> Maximum timeout for python functions

docs/ingress.md
=> document --enableTLSAcme flag

README.md
@arapulido Please check if we can publish meeting records to the bitnami youtube channel (proper youtube url ?)
=> add Community section to README

kubeless.jsonnet, script/libtest.bash
**Issue Ref**: #460 
This PR updates Kafka to the latest available image which fixes the issue found with GKE.
**TODOs**:
~~- [ ] Docs~~ (Bug fix)
=> Update Kafka image

kubeless.jsonnet, script/integration-tests
**Issue Ref**: Fixes #455
Add "kubeless" namespace to default YAML
**TODOs**:
- [NP] Automated Tests
- [NP] Docs
=> Add "kubeless" namespace to default YAML

docs/proposals/http-triggers.md
=> [PROPOSAL] http trigger improvements

kubeless.jsonnet
#475 
Patch just creates a configmap for kubeless controller and exposes the env variables in the controller.
Patch leveraging the configmap to follow.
**TODOs**:
=> kubeless.jsonnet changes to add kubless controller configmap

.travis.yml
This PR is to check that the recent errors found in the end-to-end test are not related to Travis new build environment since they just updated the default one.
**TODOs**:
~~- [ ] Docs~~
=> Use previous Travis environment

README.md
Fixes link to routing doc in README
=> fix link to routing doc

docs/GKE-deployment.md
**Issue Ref**: Fix #403
Guide of how to deploy Kubeless in a GKE cluster.
**TODOs**:
=> GKE deployment guide

docker/runtime/nodejs/Dockerfile.6, docker/runtime/nodejs/Dockerfile.8
**Issue Ref**: #510
Switched the nodejs base image from alpine to debian. As debian is using std glibc it will provide better compatibility then musl libc from alpine. 
**TODOs**:
=> Changed nodejs images from alpine to debian.

script/cluster-up-minikube.sh, script/start-gke-env.sh
Increase Minikube memory and GKE instance size.
**TODOs**:
~~- [ ] Docs~~
=> Increase resources for e2e tests

docker/runtime/dotnetcore-2.0/src/Kubeless.WebAPI/Program.cs, docker/runtime/nodejs/event-trigger/kubeless.js, docker/runtime/nodejs/http-trigger/kubeless.js, docker/runtime/python-2.7/http-trigger/kubeless.py, docker/runtime/python-3.4/http-trigger/kubeless.py, docker/runtime/ruby-2.4/event-trigger/kubeless.rb, docker/runtime/ruby-2.4/http-trigger/kubeless.rb
Here is a work-in-progress for support custom port via FUNC_PORT environment variable.
I have only tested the python runtimes, and still need to test the others, but would like some feedbacks on dotnet core runtime especially.
This is dependent by #397.
=> update runtime to use FUNC_PORT for custom port

docs/release-flow.md
Update the release-flow document to reflect pre-requisites of a release and steps to follow after doing a release.
**TODOs**:
=> Update release-flow notes

docker/runtime/python-3.6/event-trigger/Dockerfile, docker/runtime/python-3.6/event-trigger/kubeless.py, docker/runtime/python-3.6/http-trigger/Dockerfile, docker/runtime/python-3.6/http-trigger/kubeless.py
Python 3.6 runtime
Updated docker files for Python 3.6.
Added all HTTP methods, and always passing request to function.
**TODOs**:
=> Python 3.6

script/binary, script/binary-cli
**Description**:  Part of `/cmd` folder refactoring, the build script needs to be updated to take the version number in correct location.
**TODOs**:
=> build script: fix versioning

README.md
Tiny change on README to update kubeless version to v0.3.2
**TODOs**:
=> update README to v0.3.2

README.md
Seems like this [PR feature](#316) is missing. So, I add it to the document.
**TODOs**:
=> Add --env option

.travis.yml
PRs not related to Kafka should not be build. Also GKE builds should be fixed.
**TODOs**:
~~- [ ] Docs~~
=> Fix GKE travis builds and omit Kafka tests when it is unnecessary

.travis.yml, docs/release-flow.md
Update and fix some typos of the `.travis.yaml` file and `release-flow.md`.
**TODOs**:
~~- [ ] Docs~~
=> Remove typos in release flow

docs/dev-guide.md
**Issue Ref**:  None
With this PR we add some documentation about rebulding k8s manifests and a little change about the kubeless_working_dir variable.
**TODOs**:
=> Updated documentation about rebuilding k8s manifests file

examples/Makefile, tests/integration-tests-kafka.bats
Some topics are missing when running pubsub tests. We have to add them.
**TODOs**:
=> fix topic missing in pubsub tests

README.md, cmd/kubeless/function/deploy.go, cmd/kubeless/function/function.go, cmd/kubeless/function/function_test.go, cmd/kubeless/function/update.go
**Issue Ref**: [None]
**Description**: This pull request adds `--secret-names` argument to deploy and update commands. The secrets with given names will be mounted as Volumes inside pod with a Function.
**TODOs**:
=> Secrets cli

docs/README.md, docs/autoscaling.md
- Update autoscaling doc: adding overview and some comments on GKE
- Move it to under `docs` folder.
**TODOs**:
=> update autoscaling doc and move it under docs folder

pkg/utils/k8sutil.go
**Issue Ref**: https://github.com/openshift/origin/issues/17144
=> fix kubeless on openshift v3.7.0

docs/dev-guide.md
=> Fix styling of dev guide

docs/function-controller-configuration.md
**Description**: Fix sample config map for configuring function deployment  
**TODOs**:
=> Fix sample config map for configuring function deployment

.travis.yml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-6574
**TODOs**:
~~- [ ] Docs~~
=> Update Go version

chart/kubeless/Chart.yaml, chart/kubeless/README.md, chart/kubeless/templates/function-crd.yaml, chart/kubeless/templates/kubeless-config.yaml, chart/kubeless/values.yaml, docs/release-flow.md
**Issue Ref**: Fixes #600 
Update Kubeless chart to the version 0.4.0
**TODOs**:
~~- [ ] Automated Tests~~ Tested manually
=> Update Kubeless chart

examples/nodejs/function.yaml, examples/nodejs/function1.yaml, examples/python/function1.yaml, pkg/utils/k8sutil.go
=> Fix API version for functions

README.md
Add PHP as a supported runtime to README file
=> Add PHP to supported runtimes to README

kafka-zookeeper.jsonnet
Update the version of Kafka and Zookeeper
**TODOs**:
~~- [ ] Docs~~
=> [Maintenance] Update Kafka and Zookeeper

docs/quick-start.md, docs/runtimes.md
Improve docs related to the new function interface
**TODOs**:
=> Improve function interface docs

examples/Makefile, pkg/event-consumers/kafka/kafka-consumer.go, pkg/event-consumers/kafka/kafka-consumer_test.go
Minor refactor of Kafka consumer. Add unit tests.
**TODOs**:
~~- [ ] Docs~~
=> Kafka consumer tests

cmd/kubeless/function/deploy.go, cmd/kubeless/route/routeCreate.go, cmd/kubeless/route/routeDelete.go, pkg/apis/kubeless/v1beta1/http_trigger.go, pkg/controller/http_trigger_controller.go, pkg/controller/http_trigger_controller_test.go
Minor refactor of http_trigger: Now the trigger is deleted along with its targeted function.
Added unit tests.
**TODOs**:
~~- [ ] Docs~~
=> Minor refactor of http_trigger. Add unit tests

cmd/kubeless/autoscale/autoscale.go, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go, script/cluster-up-minikube.sh, script/integration-tests, script/libtest.bash
We should be testing the latest version in minikube
**TODOs**:
~~- [ ] Docs~~
=> Use default version with minikube

docs/troubleshooting.md
**Issue Ref**: #402 
Add a troubleshoot section for Kafka and Zookeeper PVs.
**TODOs**:
=> Add troubleshoot guide for Kafka and Zookeeper PV

.travis.yml, script/upload_release_notes.sh
Add kafka instructions to the release notes. The Kafka manifest was missing as well.
**TODOs**:
=> Add kafka instructions to the release notes

Makefile, cmd/kafka-trigger-controller/kafka-controller.go, cmd/kubeless-controller-manager/kubeless-controller-manager.go, cmd/kubeless/version/version.go, pkg/version/version.go, script/binary, script/binary-cli, script/binary-controller, script/kafka-controller.sh
partially address #664 
in controllers log the version of binary they are running. Its common practice for controllers to log the version they are running.
**TODOs**:
~~- [] Docs~~
=> in controllers log the version of binary they are running

.travis.yml, docs/building-functions.md, kubeless.jsonnet, pkg/controller/function_controller.go, pkg/function-image-builder/image_builder.go, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go, script/cluster-up-minikube.sh, script/integration-tests, script/libtest.bash, tests/integration-tests-prebuilt.bats
**Issue Ref**: #642 
This PR includes documentation on how to deploy a testing registry in Minikube and enable it for running end-to-end tests with the building feature.
**TODOs**:
=> Add IT and docs for local image registry

.travis.yml
The CI wasn't pushing the `latest` tag for the function builder nor the Kafka controller.
**TODOs**:
~~- [ ] Docs~~
=> Push builder and kafka latest images

.travis.yml, script/start-gke-env.sh
Fix master builds when trying to push Kafka image and clean up cluster roles that caused problems when reusing a GKE cluster.
**TODOs**:
~~- [X] Docs~~
=> Fix image push. Clean up cluster roles

.travis.yml, script/libtest.bash, tests/integration-tests-http.bats
integration test to verify basic-auth functionality 
**TODOs**:
~~- [] Docs~~
=> integration test for basic-auth with Nginx

examples/Makefile, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go, tests/integration-tests.bats
**Issue Ref**: Fixes #677 
Volume definition was being overwritten. Add unit and integration tests.
**TODOs**:
~~- [ ] Docs~~
=> Fix secrets CLI option

.gitignore, .travis.yml, Makefile, kafka-zookeeper-openshift.jsonnet, script/upload_release_notes.sh
**Issue Ref**: Ref #678 
Autogenerate zafka-zookeeper-openshift.yaml and publish it next releases.
**TODOs**:
=> Generate kafka-zookeeper-openshift.yaml

docker/runtime/golang/Dockerfile.init, docker/runtime/golang/Makefile, docker/runtime/nodejs/Dockerfile.6, docker/runtime/nodejs/Dockerfile.8, docker/runtime/nodejs/Makefile, docker/runtime/php/Dockerfile, docker/runtime/php/Makefile, docker/runtime/python/Dockerfile.2.7, docker/runtime/python/Dockerfile.3.4, docker/runtime/python/Dockerfile.3.6, docker/runtime/python/Makefile, docker/runtime/ruby/Dockerfile, docker/runtime/ruby/Makefile, docs/runtimes.md, examples/Makefile, examples/python/Dockerfile, kubeless-non-rbac.jsonnet, pkg/utils/k8sutil.go
**Issue Ref**: Fixes #674 
Change running user UID 1000.
Add securityContext for runingAsUser and fsGroup.
See #674 
cc/ @sebgoa 
**TODOs**:
=> Run functions as an unprivileged user

docs/dev-guide.md
This fixes some issue in the dev guide that someone new to the project and trying to follow the instructions closely might run into issues.
**TODOs**:
<s> - [ ] Automated Tests</s>
<s> - [ ] Docs</s>
=> Fix issues in dev guide

.travis.yml
Fixing build/ci failure. Docker tag for NATS controller was incorrect in #689
=> fix docker tag for nats controller

.travis.yml
Adding missing docker `:latest` nats controller image push from the CI
=> push nats controller image :latest tag as well

chart/kubeless/Chart.yaml, chart/kubeless/values.yaml
=> Update chart values

docs/http-triggers.md
Update Kong http-trigger documentation to use new CRDs for Consumers and Credentials.
This removes the need to make HTTP requests to the admin API.
**TODOs**:
=> Update Kong http-trigger configuration

Makefile, cmd/kubeless/function/deploy.go, cmd/kubeless/function/update.go, cmd/kubeless/getserverconfig/getServerConfig.go, docs/function-controller-configuration.md, kubeless-non-rbac.jsonnet, pkg/controller/cronjob_trigger_controller.go, pkg/controller/function_controller.go, pkg/utils/k8sutil.go, pkg/utils/k8sutil_test.go, pkg/utils/kubelessutil.go
**Issue Ref**: Continues #607 Fixes #578 
This PR updates #607 with the latest status of master. It also includes the required secrets for both the `unzip` and the `function-builder` image.
cc/ @rakesh-garimella 
**TODOs**:
=> Move unzip image to config

cmd/kubeless/function/call.go
**Issue Ref**: Fix #698
Only set the header 'application/json` if the payload is a JSON object.
**TODOs**:
~~- [] Docs~~
=> Allow plain text in calls

docs/advanced-function-deployment.md
**Issue Ref**: Fixes #598
Document YAML deployment for functions.
**TODOs**:
=> Document YAML deployment for functions

docs/use-existing-kafka.md
**Issue Ref**: Closes #196 
Update documentation related to use an existing Kafka deployment
**TODOs**:
=> Update docs for using an existing Kafka

docs/autoscaling.md, docs/debug-functions.md, docs/debug-funtions.md, docs/kubeless-functions.md, docs/pubsub-functions.md, docs/quick-start.md, docs/runtimes.md
- Review quick-start guide
- Move PubSub info out of quick-start to a new page
- Review runtimes info
- Review autoscaling info
- Add general functions info (partly covered previously in the runtimes page)
- Add guide for how to debug functions
**TODOs**:
=> Improve docs

cmd/kubeless/autoscale/autoscaleDelete.go, cmd/kubeless/autoscale/autoscaleList.go
change some typo in cmd/kubeless/autoscale,make them more understandable
=> fix cmd/kubeless/autoscale some typo

script/binary
remove all old binary, put new binary in $GOROOT/bin, print more informations when building
=> <script/binary>: print more information when building

cmd/kubeless/function/logs.go, pkg/utils/k8sutil.go
Make sure all containers in pod are ready.
And I change some typo.
=> <cmd/kubeless/logs>: change some typo and judge all containers in pod

docker/runtime/java/Dockerfile, docker/runtime/java/Dockerfile.init, docker/runtime/java/Makefile, docker/runtime/java/function/pom.xml, docker/runtime/java/function/src/main/java/io/kubeless/Example.java, docker/runtime/java/handler/pom.xml, docker/runtime/java/handler/src/main/java/io/kubeless/Handler.java, docker/runtime/java/handler/src/resources/log4j.properties, docker/runtime/java/params/pom.xml, docker/runtime/java/params/src/main/java/io/kubeless/Context.java, docker/runtime/java/params/src/main/java/io/kubeless/Event.java, docker/runtime/java/pom.xml, docs/runtimes.md, examples/Makefile, examples/java/HelloGet.java, examples/java/HelloWithData.java, examples/java/HelloWithDeps.java, examples/java/pom.xml, kubeless-non-rbac.jsonnet, pkg/langruntime/langruntime.go, tests/integration-tests.bats
**Issue Ref**: https://github.com/kubeless/kubeless/issues/7
Ths PR adds support for JAVA runtime in Kubeless. PR proposes to use `Maven` as dependency management tool. Since `Maven` is more than dependency management tool, it is also used for packaging and installing build life-cycles.
Since there is not much of code change, I will outline some of the choices and notes:
- Official`openjdk:8-jdk-alpine` image is used as base image, as it is the smallest.
- Maven is not part of the base image, so additional step is used to install Maven.
- below java project layout is used
```
docker/runtime/java
├── Dockerfile
├── Dockerfile.init
├── Makefile
├── function
│   ├── pom.xml
│   └── src
│       └── main
│           └── java
│               └── io
│                   └── …
```
=> java support with prometheus and dependency management with maven

.circleci/config.yml
Add missing docker setup in the GKE scenario
**TODOs**:
~~- [] Docs~~
=> [circleci] Setup docker in GKE build

cmd/kubeless/function/call.go, cmd/kubeless/function/delete.go, cmd/kubeless/function/deploy.go, cmd/kubeless/function/describe.go, cmd/kubeless/function/function.go, cmd/kubeless/function/function_test.go, cmd/kubeless/function/logs.go, cmd/kubeless/function/update.go
Added some common shorthand flags like `-f` for the file, `-n` for the namespace or `-d` for `--data`.
I also removed an unused parameter in the `getFunctionDescription` function.
**TODOs**:
~~- [ ] Docs~~
=> Add shorthand flags

docs/quick-start.md
=> fix function name in quick start

.circleci/config.yml, script/create_release.sh, script/release_utils.sh
Kinesis YAML was missing from the release process. Avoid duplicated manifest list. Other minor fixes.
**TODOs**:
~~- [ ] Docs~
=> Add kinesis yaml in the release process. Other minor fixes

CONTRIBUTING.md
=> fix slack link

examples/Makefile, tests/integration-tests.bats
**Issue Ref**: #750 
Add a new integration test for the nodejs_distroless runtime which tests dependencies.
Integration test for the nodejs_distroless runtime covering dependency use case.
**TODOs**:
- [ x] Ready to review
- [ x] Automated Tests
=> add integration test: get-nodejs-distroless-deps

docs/advanced-function-deployment.md
**Issue Ref**: #797
Explain how to overcome the 1MB limitation for functions.
**TODOs**:
=> Update adv deployment doc

docker/runtime/ballerina/Ballerina.toml, docker/runtime/ballerina/Dockerfile, docker/runtime/ballerina/Dockerfile.init, docker/runtime/ballerina/Makefile, docker/runtime/ballerina/kubeless/kubeless.bal, docs/runtimes.md, examples/Makefile, kubeless-non-rbac.jsonnet, pkg/langruntime/langruntime.go
Update ballerina runtime version to 0.975.0 
**TODOs**:
=> Update ballerina runtime version to 0.975.0

docker/runtime/ballerina/Dockerfile.init, docker/runtime/ballerina/compile-function.sh, kubeless-non-rbac.jsonnet, pkg/langruntime/langruntime.go
Move Ballerina compilation steps to an script. Only `touch` `kubeless.toml` file if it doesn't exists.
cc/ @anuruddhal 
**TODOs**:
~~- [ ] Docs~~
=> Move ballerina compilation to a script

docs/runtimes.md, examples/nodejs/function.yaml, examples/nodejs/function1.yaml
=> Fixes in documentation

docker/runtime/ballerina/Ballerina.toml, docker/runtime/ballerina/Dockerfile, docker/runtime/ballerina/Dockerfile.init, docker/runtime/ballerina/Makefile, docker/runtime/ballerina/compile-function.sh, docker/runtime/ballerina/kubeless/Package.md, docker/runtime/ballerina/kubeless/kubeless.bal, docker/runtime/ballerina/kubeless_run.tpl.bal, docs/runtimes.md, examples/Makefile, kubeless-non-rbac.jsonnet
- Update ballerina runtime to 0.980.0
**TODOs**:
=> Update ballerina runtime to 0.980.0

docker/runtime/ballerina/Makefile, kubeless-non-rbac.jsonnet
- Update ballerina docker registry
**TODOs**:
=> Update ballerina docker registry

cmd/kubeless/function/deploy.go, cmd/kubeless/function/update.go, cmd/kubeless/trigger/cronjob/create.go, cmd/kubeless/trigger/cronjob/delete.go, cmd/kubeless/trigger/cronjob/update.go, cmd/kubeless/trigger/http/create.go, cmd/kubeless/trigger/http/delete.go, cmd/kubeless/trigger/http/update.go, cmd/kubeless/trigger/kafka/create.go, cmd/kubeless/trigger/kafka/delete.go, cmd/kubeless/trigger/kafka/update.go, cmd/kubeless/trigger/kinesis/create.go, cmd/kubeless/trigger/kinesis/delete.go, cmd/kubeless/trigger/kinesis/publish.go, cmd/kubeless/trigger/kinesis/stream_create.go, cmd/kubeless/trigger/kinesis/update.go, cmd/kubeless/trigger/nats/create.go, cmd/kubeless/trigger/nats/delete.go, cmd/kubeless/trigger/nats/update.go, glide.yaml, pkg/utils/kubelessutil.go
=> [WIP] dryrun

.circleci/config.yml, pkg/utils/k8sutil.go
**Issue Ref**: #869 
Fix config initialization when several paths are set in the `KUBECONFIG` env var.
**TODOs**:
~~- [ ] Docs~~
=> Fix several paths in KUBECONFIG

cmd/kubeless/function/list.go
**Issue Ref**: Fixes #874 
Print function list as an array
**TODOs**:
~~- [ ] Docs~~
=> List functions as an array

docker/runtime/ballerina/Ballerina.toml, docker/runtime/ballerina/Dockerfile, docker/runtime/ballerina/Dockerfile.init, docker/runtime/ballerina/Makefile, docker/runtime/ballerina/kubeless/Package.md, docs/runtimes.md, examples/Makefile, kubeless-non-rbac.jsonnet
- Update Ballerina version to 0.981.0
**TODOs**:
=> Update Ballerina version to 0.981.0

docs/quick-start.md
**Issue Ref**: #893
Point to RBAC manifest in the quick start guide
**TODOs**:
=> Point to RBAC manifest in quick start guide

docs/runtimes.md
**Issue Ref**: #900
Document how to create custom runtimes based on official ones.
**TODOs**:
=> Document custom runtime flavors

examples/nodejs/package.json
Avoid warning.
**TODOs**:
~~- [ ] Docs~~
=> Update sample package.json

.circleci/config.yml, Makefile
```
can't load package: package github.com/golang/lint/golint: code in directory /home/circleci/.go_workspace/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```
**TODOs**:
=> Avoid error installing golint

docker/runtime/jvm/Readme.md, docs/advanced-function-deployment.md, docs/implementing-new-runtime.md, docs/streaming-functions.md
**Issue Ref**: 
None. 
This PR fix some typo and description of maximum size of etcd record.
=> docs: fix typo && maximum size of etcd record

pkg/langruntime/langruntime.go, tests/integration-tests-cronjob.bats
Allow underscore in runtimes. Remove flaky test for cronjob cleanup.
**TODOs**:
~~- [ ] Docs~~
=> Allow underscore in runtimes. Remove flaky test

.circleci/config.yml
After discussion at [997](https://github.com/kubeless/kubeless/pull/997#issuecomment-460950849)
**TODOs**:
=> use go 1.11 for building

docs/quick-start.md
Fix typo in quick-start.md.
**TODOs**:
=> Fix typo in quick-start.md

kubeless-non-rbac.jsonnet
**Issue Ref**: #934
Bump HTTP trigger controller version to support CORS requests.
**TODOs**:
~~- [ ] Docs~~
=> Bump http-trigger controller version

cmd/function-controller/function-controller.go
None 
fix 404 not fund
fix 404 not fund
**TODOs**:
=> Fix 404 not fund

script/validate-vet
golang/go#23916
#1018 
#1012
Change 'go vet' to 'go tool vet', so that we can make CI pass.
**TODOs**:
=> Change 'go vet' to 'go tool vet'

cmd/kubeless/autoscale/autoscale.go, cmd/kubeless/autoscale/autoscaleList_test.go, cmd/kubeless/completion/completion.go, cmd/kubeless/function/function.go, cmd/kubeless/topic/topic.go, cmd/kubeless/trigger/trigger.go, cmd/kubeless/version/version.go
Improve code format for comment
Improve code format for comment
**TODOs**:
=> Improve code format for comment

docs/quick-start.md
**Issue Ref**: https://github.com/kubeless/kubeless/issues/83#issuecomment-486754640
Update the quick-start guide to obtain available runtimes.
**TODOs**:
~~- [X] Automated Tests~~
=> Update info to retrieve available runtimes

docs/runtimes.md
**Issue Ref**: #1026 
Quick Documentation update
**TODOs**:
=> updated custom runtime documentation links

docker/unzip/Dockerfile, kubeless-non-rbac.jsonnet
Update `unzip` image,  migrate it to `minideb` to avoid possible security issues.
**TODOs**:
~~- [] Docs~~
=> Replace base image for unzip

.circleci/config.yml, script/cluster-up-minikube.sh
**Issue Ref**: #1049 
Upgrade the current minikube version and test the latest version of Kubernetes (1.15).
**TODOs**:
~~- [ ] Docs~~
=> Upgrade Minikube version

kubeless-non-rbac.jsonnet
**Issue Ref**: Close #1049
Use latest versions of the HTTP and CronJob trigger controllers.
**TODOs**:
~~- [ ] Docs~~
=> Update http and cronjob trigger controllers

kubeless-non-rbac.jsonnet
**Issue Ref**: #1086
Use `apps/v1` for the deployment apiVersion
**TODOs**:
~~- [ ] Docs~~
=> Use new endpoint for the current deployment

docs/function-controller-configuration.md
Fixes link to k8s API reference.
**TODOs**:
=> Fix link to K8s API reference

docs/function-controller-configuration.md
**Issue Ref**: #1148 
**Description**: The changes herein address the issue raised in #1148
=> fix: function controller config spec template

docs/architecture.md
update yaml output of CRD functions.kubeless.io
**TODOs**:
=> update yaml output of CRD functions.kubeless.io

docs/streaming-functions.md
update the url of kinesis-trigger manifest
=> update the url of kinesis-trigger manifest

docs/triggers.md
add Kafka Trigger and AWS Kinesis Trigger to Available triggers
=> update  available triggers

docs/pubsub-functions.md
update the deployment.yaml url of NATS operator
=> update the deployment.yaml url of NATS operator

docs/dev-guide.md
=> add AWS Kinesis Trigger

docs/http-triggers.md
update the deployment url of Kong
=> update the deployment url of Kong

docs/debug-functions.md
update kubectl logs cmmand and it's output
=> update kubectl logs cmmand and it's output

kubeless-non-rbac.jsonnet
**Issue Ref**: #1213
Update http and cronjob trigger controllers to release a new version.
**TODOs**:
~~- [ ] Docs~~
=> Update trigger controllers

docs/implementing-new-trigger.md
Easy navigation and easy reading for others
=> Fix broken url in docs

docs/cronjob-triggers.md
Just ran across this in the docs -- cheers
=> Fix install link for CronJob trigger example func

docs/quick-start.md
Found while delving in into the tool and was quite annoying to discover for someone with no experience with the tool and few experience with k8s.
**TODOs**:
=> Update quick-start to supported python (3.8)
